microsoft/teams-ai

js/packages/teams-ai/src/TaskModules.ts
As a response to the task/submit invoke, Teams expects [either a HTTP 200 with no payload (meaning success), a string or a new TaskInfo object](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=nodejs#responds-to-the-tasksubmit-messages). Currently the TaskModules submit() method returns this if there is no string or object:
```
response = {
task: undefined
}
```
which is not valid and causes the backend to send this error to Teams:
```
{"errorCode":1008,"message":"<BotError>Error when processing invoke response: Task or Task Type is missing in Task Module response","standardizedError":{"errorCode":1008,"errorSubCode":1,"errorDescription":"<BotError>Error when processing invoke response: Task or Task Type is missing in …
```
=> Fix case where adaptive card task module does not return anything

js/samples/01.messaging.a.echoBot/web.config, js/samples/02.messageExtensions.a.searchCommand/web.config, js/samples/03.adaptiveCards.a.typeAheadBot/web.config, js/samples/04.ai.a.teamsChefBot/web.config, js/samples/04.ai.b.messageExtensions.gptME/web.config, js/samples/04.ai.c.actionMapping.lightBot/web.config, js/samples/04.ai.d.chainedActions.listBot/web.config, js/samples/04.ai.e.chainedActions.devOpsBot/web.config, js/samples/04.e.twentyQuestions/web.config, js/samples/04.q.questBot/web.config
I recently tried to deploy some of these samples to Azure using Teams Toolkit. However, the apps do not start properly since the Bicep file creates Windows App Services, yet there is no `web.config` overrride to point the IIS Server to the right JS start file. I copied a sensible `web.config` which is also used by other Teams samples to ensure users do not have trouble deploying these samples to Azure.
=> Add web.config to all samples to ensure Azure deployment works

dotnet/packages/Microsoft.Bot.Builder.M365/Microsoft.Bot.Builder.M365.Tests/TypingTimerTests.cs, dotnet/packages/Microsoft.Bot.Builder.M365/Microsoft.Bot.Builder.M365/Application.cs, dotnet/packages/Microsoft.Bot.Builder.M365/Microsoft.Bot.Builder.M365/TypingTimer.cs
Made a few changes to the TypingTimer based on @vule-msft's suggestions
* It implements the `IDisposable` interface to follow C# conventions on object that need to have resources explicitly disposed by the users.
* Implemented a destructor to properly dispose the timer resource when garbage collector destroys this object
* Made timer property private to avoid unexpected mutations from outside this class
=> Typing Timer update

.github/workflows/dotnet-ci.yml, .github/workflows/dotnet-pr.yml
For https://github.com/microsoft/teams-ai/issues/210.
GitHub detects workflows from the default branch. This PR adds place holders to `main` branch, while https://github.com/microsoft/teams-ai/pull/222 adds detailed dotnet workflows to `DOTNET` branch.
=> add place holders for dotnet workflows

dotnet/packages/Microsoft.Bot.Builder.M365/Microsoft.Bot.Builder.M365.Tests/AITests/OpenAIModeratorTests.cs, dotnet/packages/Microsoft.Bot.Builder.M365/Microsoft.Bot.Builder.M365.Tests/AITests/OpenAIPlannerTests.cs, dotnet/packages/Microsoft.Bot.Builder.M365/Microsoft.Bot.Builder.M365.Tests/AITests/PromptManagerTests.cs, dotnet/packages/Microsoft.Bot.Builder.M365/Microsoft.Bot.Builder.M365.Tests/IntegrationTests/AzureOpenAIPlannerTests.cs, dotnet/packages/Microsoft.Bot.Builder.M365/Microsoft.Bot.Builder.M365.Tests/IntegrationTests/OpenAIModeratorTests.cs, dotnet/packages/Microsoft.Bot.Builder.M365/Microsoft.Bot.Builder.M365.Tests/IntegrationTests/OpenAIPlannerTests.cs, dotnet/packages/Microsoft.Bot.Builder.M365/Microsoft.Bot.Builder.M365/AI/Moderator/OpenAIModerator.cs, dotnet/packages/Microsoft.Bot.Builder.M365/Microsoft.Bot.Builder.M365/AI/Moderator/OpenAIModeratorOptions.cs, dotnet/packages/Microsoft.Bot.Builder.M365/Microsoft.Bot.Builder.M365/AI/OpenAI/OpenAIClient.cs, dotnet/packages/Microsoft.Bot.Builder.M365/Microsoft.Bot.Builder.M365/AI/OpenAI/OpenAIClientOptions.cs, dotnet/packages/Microsoft.Bot.Builder.M365/Microsoft.Bot.Builder.M365/Exceptions/OpenAIClientException.cs
- rename DefaultModel to Model in OpenAIModeratorOptions
- remove DefaultModel from OpenAIClientOptions
- add unit test for OpenAI moderator
- add integration test for OpenAI moderator
Resolves https://github.com/microsoft/teams-ai/issues/213
=> Add tests for OpenAI moderator

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/StateTests/TurnStateManagerTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/TypingTimerTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/State/TurnStateManager.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/TypingTimer.cs
https://github.com/microsoft/teams-ai/issues/271 to track. I found these issues when creating sample.
- In state manager, use correct storage key to delete state entry from storage.
- In typing timer, treat `TaskCanceledException` as expected since `turnContext.SendActivityAsync` may be canceled when current turn finished.
=> fix: fix typing timer and state bugs

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/PromptManagerTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/ConversationHistoryTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/TestUtils/CustomTurnState.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Prompt/PromptManager.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/ApplicationOptions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/State/ITurnState.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/State/TurnState.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/State/TurnStateManager.cs
If a custom turn state class was used, the temporary `input`, `history` & `output` values would not have been injected into the prompt template. This PR fixes that bug and adds a corresponding unit test
=> fix custom turn state bug

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/TypingTimerTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/TypingTimer.cs
Found this https://github.com/microsoft/teams-ai/issues/329 when debugging sample.
Add NullReferenceException to ignore list as well.
=> [C# fix] Ignore NullReferenceException in TypingTimer

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/AITests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/OpenAIPlannerTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/TestUtils/TestModerator.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/TestUtils/TestPlanner.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/TestUtils/TestPromptManager.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/AI.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Planner/OpenAIPlanner.cs
For https://github.com/microsoft/teams-ai/issues/233
- Add unit tests for `AI.cs` (19.2% -> 88.0%) and `OpenAIPlanner.cs` (41.1% -> 81.7%).
- Fix code warnings in `AI.cs` and `OpenAIPlanner.cs`.
- Fix a non-blocking issue in `AI.cs` to use configured options instead of pass-in options.
=> [C#] Add unit tests for AI classes

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Planner/AzureOpenAIPlannerOptions.cs, dotnet/samples/README.md, js/.nycrc, js/.vscode/settings.json, js/package.json, js/packages/teams-ai/src/AzureOpenAIPlanner.ts, js/packages/teams-ai/src/ConversationHistory.spec.ts
1. Resolves #424 (as a stop-gap between updates)
1. Add information for `defaultModel` in   `AzureOpenAIPlannerOptions` so users know what deployment/model name to use.
2. This is a mitigation until #394 is resolved.
1. #54 
1. Minor cleanup of test scripts
2. !! Add questions for discussion on `ConversationHistory` implementation for `clear()` behavior and `replaceLastSay()`
1. (no work item) Update `dotnet/samples/README.md` for clarity
=> Minor updates

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/ActionHandlerTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/ActivityHandlerTests/ActivityHandlerTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/AI.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Action/ActionEntry.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Action/ActionHandler.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Action/DefaultActions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Prompt/PromptTemplateConfiguration.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/TypingTimer.cs
Resolve https://github.com/microsoft/teams-ai/issues/416
- For argument check, throw `ArgumentException` or `ArgumentNullException`
- For `AI` methods, throw `AIException`
- For Prompt, throw `PromptManagerException`
- For other runtime unexpected behavior, throw `InvalidOperationException`
=> [C#] Replace base Exception with more specific exception

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/StateTests/TurnStateEntryTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/AzureContentSafety/AzureContentSafetyClient.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/OpenAI/OpenAIClient.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/State/TurnStateEntry.cs
#414  made all instances of `JsonSerializerOptions` as singleton by making it a private static property in the class where it is used. This is for performance reasons. 
[Article on performance difference](https://www.meziantou.net/avoid-performance-issue-with-jsonserializer-by-reusing-the-same-instance-of-json.htm)
=> Make json serializer options object a singleton instance

python/packages/ai/teams/ai/state/conversation_history.py
The `to_str` function does not use a tokenizer, so the calculation of used tokens will be inaccurate. This PR uses the recommended tokenizer to encode and calculate the total tokens.
@aacebo I'm not sure whether it's on purpose to just use `len()`. If yes, you can close this PR directly without merge.
=> fix: not using tokenizer in ConversationHistory.to_str()

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/PlanTests.cs
fixes: #505 
This is a patch to failing Plan tests
=> [C#] fix: normalize line endings to fix Plan tests failing

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/AITests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/AI.cs
Fixes #490
Fix the missing temp variables when calling `AI.CompletePromptAsync()`.
- Call `_SetTempStateValues` to set `input` and `history`
- Add unit test to cover this fix
=> [C#] fix: fix missing built-in variables

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/AIHistoryOptions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Action/ActionEntry.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Action/DoCommandActionData.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Moderator/ModerationResponse.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/OpenAI/OpenAIClient.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/OpenAI/OpenAIClientOptions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Planner/ParsedCommandResult.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Prompt/SKFunctionWrapper.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Prompt/TemplateFunctionEntry.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Exceptions/HttpOperationException.cs
closes: #531  (issue number)
Internalized
- OpenAIClient: We don't expect end users to use our open ai client to directly call the api. They should use other existing libraries for this.
- OpenAIClientOptions: Part of the OpenAI client
- DoCommandActionData: a helper class
Sealed
- A bunch of classes we don't expect the end user to extend.
The motivation behind aggressively sealing/internalizing classes is to prevent end users from relying on components we don't explicitly expect them using. Eg. The OpenAIClient's sole purpose is to service the OpenAIModerator, even though end users can use it to directly call the API. 
If there's a legitimate reason or customer ask to unseal/publicize …
=> [C#] feat: seal/internalize non-essential classes

.github/workflows/pr-style.yml, CONTRIBUTING.md
#minor
Remove ":" from keyword requirement on PRs for bumping packages. 
This is done to reduce overhead for `dependabot` PRs, which always have 'bump' in the title anyway.
=> [repo] chore: Remove ':' from PR keywords requirement when bumping packages

.github/CODEOWNERS, .github/CODEOWNERS.md
#minor
- remove `.md` file, currently `CODEOWNERS.md` is not being picked up by github because the file should not be a markdown file.
- add codeowners for different languages
=> [repo] chore: update codeowners

python/packages/ai/teams/adaptive_cards/adaptive_cards.py, python/packages/ai/teams/ai/ai.py, python/packages/ai/teams/app.py, python/packages/ai/teams/message_extensions.py, python/packages/ai/teams/task_modules/task_modules.py, python/samples/03.adaptiveCards.a.typeAheadBot/src/app.py
closes: #565 
Add type annotation for decorator return value so mypy can get enough information to do type checking.
=> [PY] feat: add type annotation for decorators to support mypy

python/packages/ai/.pylintrc, python/packages/ai/teams/ai/ai.py, python/packages/ai/teams/ai/models/azure_openai/client/__init__.py, python/packages/ai/teams/ai/models/azure_openai/client/azure_openai_client.py, python/packages/ai/teams/ai/models/azure_openai/planner.py
closes: https://github.com/microsoft/teams-ai/issues/622
- add azure openai client for content safety
- temporarily disable azure openai moderation methods to unblock chefbot
=> [PY] fix: add azure client and disable moderation in azure planner

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/AdaptiveCardsTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/AdaptiveCards.cs
closes: #601 
- use `AdaptiveCardInvokeResponse` as return type of `ActionExecuteHandler`. The change is because the original style cannot meet the following requirement: return values with different types in one handler. For example, if I'd like to return Adaptive Card or text message by some cases in `OnActionExecute("verb")`, I have to define `OnActionExecute("verb", ActionExecuteAdaptiveCardHandler)` and `OnActionExecute("verb", ActionExecuteTextHandler)` respectively. Although the two handlers will be hit, only one result will be returned. A concrete example is `SubmitAction` in gptME sample.
- I have made corresponding changes to the documentation (we use …
=> [C#] refactor: return AdaptiveCardInvokeResponse for ActionExecute

js/packages/teams-ai/src/Application.spec.ts, js/packages/teams-ai/src/Application.ts, js/packages/teams-ai/src/MessageExtensions.spec.ts, js/packages/teams-ai/src/MessageExtensions.ts, js/packages/teams-ai/src/TaskModules.ts
closes: #741
other: #744
- Fixes a task module bug I introduced that @lilyydu caught -- thanks Lily!
- For Teams-only events, make sure that `channelId` is verified
```typescript
case 'teamRenamed':
case 'teamDeleted':
case 'teamHardDeleted':
case 'teamArchived':
case 'teamUnarchived':
case 'teamRestored':
/**
* @param {TurnContext} context The context object for the current turn of conversation.
* @returns {Promise<boolean>} A Promise that resolves to a boolean indicating whether the activity is a conversation update event related to teams.
*/
return (context: TurnContext) => {
return Promise.resolve(
context?.activity?.channelId === 'msteams' && // this change here …
```
=> [JS] fix: #741 #744 Fix task modules bug in JS and add filtering for teams channel events

js/packages/teams-ai/src/MessageExtensions.spec.ts, js/packages/teams-ai/src/MessageExtensions.ts
#minor
`messageExtensions.handleOnButtonClicked` had third parameter named `settings` which is a copy-paste error. This updates it to `data`.
=> [JS] fix: parameter passing in Message Extensions handleOnButtonClicked was confusingly named

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/ApplicationBuilderTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/ApplicationTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/ApplicationBuilder.cs, dotnet/samples/04.ai.b.messageExtensions.gptME/Program.cs, dotnet/samples/04.e.twentyQuestions/Program.cs, getting-started/dotnet/00.MIGRATION.md
closes: #710
associated: #615
associated JS changes (already merged): #651 
- Added the `ApplicationBuilder` class, and associated tests 
- Added in missing tests for `Application` construction 
- Updated docs
- Updated 2 samples (04.ai.b.messageExtensions.AI-ME and 04.e.twentyQuestions) to use builder pattern
=> [C#] feat: ApplicationBuilder Implementation

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/ApplicationRouteTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Application.cs
#minor (avoid closing issue)
associated: #744
Check channel id "msteams" for teams-specific events
```csharp
// add check
string.Equals(context.Activity?.ChannelId, Channels.Msteams)
```
=> [C#] fix: check channel id "msteams" for teams-specific events

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/AdaptiveCardsTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/ApplicationRouteTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/MessageExtensionsTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/TaskModulesTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Application.cs
closes: #761 
- messageUpdate - editMessage
- messageUpdate - undeleteMessage
- messageDelete - softDeleteMessage
Reference: https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs#L903
=> [C#] feat: handles message update/delete events

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Microsoft.TeamsAI.Tests.csproj
#minor
related: #418
Dependabot bumps moq to 4.20 in https://github.com/microsoft/teams-ai/pull/593. This PR is to downgrade it back to 4.18
```
<PackageReference Include="Moq" Version="4.18.4" />
```
=> [C#] fix: downgrade moq to 4.18

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/ApplicationRouteTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Application.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/ConversationUpdateEvents.cs
closes: #610 
associated: #708 
Provide handling for all ConversationUpdate events (previously, only `membersAdded` and `membersRemoved`).
- Added missing ConversationUpdate events - `teamHardDeleted`, `topicName` and `historyDisclosed`
- Added routing for missing channel and team activity events 
- Added associated tests for these routes
- New and existing unit tests pass locally with my …
=> [C#] feat: Add handling to missing ConversationUpdate events

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/ApplicationRouteTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Application.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/ConfigHandler.cs
closes: #605 
- config/fetch
- config/submit
Reference: https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs#L95.
Do not separate the response types (auth and task module) into two handlers like OnConfigFetchAuth and OnConfigFetchTask because it seems that there are no useful information in Activity.Value to distinguish them. Thus, just simply pass Activity.Value to handler then return invoke response based on handler result.
- I have made corresponding changes to the documentation (we use [TypeDoc](https://typedoc.org/) …
=> [C#] feat: handles config events 

js/packages/teams-ai/src/Application.spec.ts, js/packages/teams-ai/src/Application.ts, js/packages/teams-ai/src/MessageExtensions.spec.ts, js/packages/teams-ai/src/MessageExtensions.ts, js/packages/teams-ai/src/TaskModules.spec.ts, js/packages/teams-ai/src/TaskModules.ts
closes: #635
closes: #247 
- A behavior that was missing from Task Modules was handling submit "continue" scenario when the handler does not return a `TaskModuleResponse` or string. This ensures that the expected response (empty 200) is sent even if there is nothing new to render/send. 
- Modify so that Teams events check for channelId using `Channels` enum, not 'msteams' string
- This included minor refactor for Message Extension and Application as well
- Add Task Module tests to get the file to 80% coverage
- I have added tests that …
=> [JS] fix: #247 #635 Add fallthrough for empty result Task Module Fetch and tests

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/MeetingsTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/ActivityUtilities.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/AdaptiveCards/AdaptiveCards.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Application.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Meetings/Meetings.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Meetings/MeetingsHandlers.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/MessageExtensions/MessageExtensions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/TaskModules/TaskModules.cs
closes: #696
Add handlers for meeting events
Add handlers under `Application.Meetings` for following events:
- application/vnd.microsoft.meetingStart
- application/vnd.microsoft.meetingEnd
- application/vnd.microsoft.meetingParticipantJoin
- application/vnd.microsoft.meetingParticipantLeave
Refactor `InvokeActivityUtilities` to `ActivityUtilities` since the event activity has `Activity.Value` as well.
Unit tests. …
=> [C#] feat: add meeting handlers

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/MemoryTests/MemoryTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Memory/Memory.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj
#minor
https://github.com/microsoft/teams-ai/issues/721
add memory class
In the JS implementation there is a `Memory` interface and a `MemoryFork` class which implements it. To simplify things I opted to just have a `Memory` class which is the default implementation, and can be inherited if a developer wants to customize it.
=> [C#] chore: Add Memory Class

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/ApplicationRouteTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Application.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/FileConsentCardHandler.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/O365ConnectorCardActionHandler.cs
closes: #606
Add handlers for:
- `fileConsent/invoke`
- `actionableMessage/executeAction`
Added 3 methods to `Application`:
- `OnFileConsentAccept`
- `OnFileConsentDecline`
- `OnO365ConnectorCardAction`
Added unit tests
=> [C#] feat: add file and o365 card handlers

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/ApplicationRouteTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Application.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/ReadReceiptHandler.cs
closes: #697 
- Added handling of read receipt events in personal scope, and associated tests. 
**Delegate:**
Task ReadReceiptHandler(ITurnContext turnContext, TState turnState, ReadReceiptInfo data, CancellationToken cancellationToken)
**API:**
OnTeamsReadReceipt(ReadReceiptHandler<TState> handler)
**Reference:**
[BotBuilder Code](https://github.com/microsoft/botbuilder-dotnet/blob/e4afa430ea73dd725be39a30d16fe361e77d07c8/libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs#L807)
[BotBuilder PR](https://github.com/microsoft/botbuilder-dotnet/pull/6356)
- My …
=> [C#] feat: Add Handler for Read Receipt Event

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/OpenAIClientAssistantTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/OpenAIClientTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/OpenAIClientThreadTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Microsoft.Teams.AI.Tests.csproj, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/OpenAI/Models/Assistant.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/OpenAI/Models/ListResponse.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/OpenAI/Models/Message.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/OpenAI/Models/Run.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/OpenAI/Models/Thread.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/OpenAI/Models/Tool.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/OpenAI/OpenAIClient.Assistant.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/OpenAI/OpenAIClient.Thread.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/OpenAI/OpenAIClient.cs
#minor (avoid closing issue)
closes: #798
Since OpenAI does not officially have .NET SDK, this PR adds OpenAI Assistant and Thread API calls to `OpenAIClient`
- Call OpenAI's Assistant and Thread APIs
- Seperate into partial `OpenAIClient` class
- Only add APIs that will be called in `AssistantPlanner`
> Feel free to add other …
=> [C#] feat: call OpenAI's assistant and thread APIs

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/AddHeaderRequestPolicy.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/AddQueryRequestPolicy.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/AzureOpenAIModelOptions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/AzureSdkChatMessageExtensions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/BaseOpenAIModelOptions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/ChatMessageExtensions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/ConfiguredDelayStrategy.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/IPromptCompletionModel.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/OpenAIModel.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/OpenAIModelOptions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/RequestFailedExceptionExtensions.cs
closes: #723 
- BaseOpenAIModelOptions
- OpenAIModelOptions
- AzureOpenAIModelOptions
- IPromptCompletionModel
- OpenAIModel
Followings are different from JS part:
- use Azure.AI.OpenAI instead of http requests
- remove requestConfig from BaseOpenAIModelOptions, but instead pass HttpClient in OpenAIModel constructor
- remove endpoint from OpenAIModelOptions because it is not supported by Azure.AI.OpenAI
TODOs in PRs afterwards:
- support logging colorized contents
- unit test
- I have added tests that validates my changes, and …
=> [C#] refactor: add OpenAIModel

js/packages/teams-ai/src/Application.ts, js/packages/teams-ai/src/Meetings.ts
closes: #668
- Add a new class, `Meetings.ts`, for handling Teams meeting events
- `start`
- `end`
- `participantsJoin`
- `participantsLeave` 
- Add `teamsReadReceipt` handler for Teams read receipt information
-  After turnStateManager rename to `turnStateFactory`, add options configuration for Application Builder's `turnStateFactory`
- New and existing unit tests pass locally with my …
=> [JS] feat: #668 Add Meetings event handlers, read receipt handler, and Application Builder's turnStateFactory

js/packages/teams-ai/src/authentication/AdaptiveCardAuthenticationBase.ts, js/packages/teams-ai/src/authentication/Authentication.ts, js/packages/teams-ai/src/authentication/BotAuthenticationBase.ts, js/packages/teams-ai/src/authentication/MessageExtensionAuthenticationBase.ts, js/packages/teams-ai/src/authentication/OAuthAdaptiveCardAuthentication.ts, js/packages/teams-ai/src/authentication/OAuthBotAuthentication.ts, js/packages/teams-ai/src/authentication/OAuthMessageExtensionAuthentication.ts, js/packages/teams-ai/src/authentication/TeamsBotSsoPrompt.ts, js/packages/teams-ai/src/authentication/TeamsSsoAdaptiveCardAuthentication.ts, js/packages/teams-ai/src/authentication/TeamsSsoBotAuthentication.spec.ts, js/packages/teams-ai/src/authentication/TeamsSsoBotAuthentication.ts, js/packages/teams-ai/src/authentication/TeamsSsoMessageExtensionAuthentication.ts, js/packages/teams-ai/src/authentication/TeamsSsoSettings.ts
closes: #849
1. Add JSDoc for authentication code
2. Move `TeamsSsoSettings` out of `TeamsBotSsoPromt`, as it's not only for this prompt
=> [JS] feat: add jsdoc for authentication code

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/AssistantsPlannerTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/TestUtils/TestAssistantsOpenAIClient.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Planners/AssistantsPlanner.cs
closes: #892
Fix the message order of Assistant's response.
Reverse the messages returned from OpenAI's `listMessages` API
=> [C#] fix: assistant message order

js/packages/teams-ai/src/planners/index.ts, js/samples/06.assistants.a.mathBot/src/bot.ts, js/samples/06.assistants.b.orderBot/src/bot.ts
closes: #906 
Exports the _AssistantsPlanner.ts_ file like this: 
```js
export * as preview from "./AssistantsPlanner.ts"
```
Samples consume it like this:
```js
import { preview } from "@microsoft/teams-ai"
const { AssistantsPlanner } = preview
```
=> [JS] chore: Change assistants planner scope to "preview"

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Clients/LLMClient.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/OpenAIModel.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Prompts/PromptResponse.cs
closes: #915 
- use TeamsAIException instead of bot schema error for PromptResponse.Error
=> [C#] fix: use TeamsAIException for PromptResponse.Error

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/AssistantsPlannerTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Planners/AssistantsPlanner.cs
closes: #925
Fix `KeyNotFound` exception when executed actions are more than assistant required actions.
- Only submit required actions and ignore others
- UT added
=> [C#] fix: ignore redundant action when submitting tool outputs

js/packages/teams-ai/src/planners/AssistantsPlanner.ts
closes: #925
Fix the missing `tool_call_id` issue when a turn contains multiple assistant runs
- One turn may execute several actions, but may some of them are required for assistant. Only return required tool calls to assistant.
=> [JS] fix: assistant tool_outputs

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/Authentication/Bot/BotAuthenticationBaseTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/Authentication/MessageExtensions/MessageExtensionsAuthenticationBaseTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/Authentication/MockedAuthentication.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Application.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/ApplicationOptions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/AdaptiveCards/AdaptiveCardsAuthenticationBase.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/AdaptiveCards/OAuthAdaptiveCardsAuthentication.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/AdaptiveCards/TeamsSsoAdaptiveCardsAuthentication.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/AuthUtilities.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/AuthenticationManager.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/AuthenticationOptions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/Bot/BotAuthenticationBase.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/Bot/OAuthBotAuthentication.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/Bot/TeamsSsoBotAuthentication.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/Bot/TeamsSsoPrompt.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/IAuthentication.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/MessageExtensions/MessageExtensionsAuthenticationBase.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/MessageExtensions/OAuthMessageExtensionsAuthentication.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/MessageExtensions/TeamsSsoMessageExtensionsAuthentication.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/OAuthAuthentication.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/TeamsSsoAuthentication.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/TeamsSsoSettings.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/TurnStateProperty.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/State/TempState.cs
closes: #861
1. Implement token exchange and sign in logic for Teams SSO auth implementation
2. Updated the `IAuthentication` interface to initialize after `Application` instance is created - the authentication classes has dependency to `Application` when initialize
3. Change visibility of some classes to `internal`
4. Update the namespace of authentication classes to `Microsoft.Teams.AI` to align with other classes under the `Application` folder
- I have added tests that validates my changes, and provides sufficient test coverage. I …
=> [C#] feat: add teams sso implementation

dotnet/samples/06.auth.teamsSSO.messageExtension/.gitignore, dotnet/samples/06.auth.teamsSSO.messageExtension/AdapterWithErrorHandler.cs, dotnet/samples/06.auth.teamsSSO.messageExtension/Config.cs, dotnet/samples/06.auth.teamsSSO.messageExtension/Controllers/BotController.cs, dotnet/samples/06.auth.teamsSSO.messageExtension/MessageExtensionAuth.csproj, dotnet/samples/06.auth.teamsSSO.messageExtension/MessageExtensionAuth.sln, dotnet/samples/06.auth.teamsSSO.messageExtension/Model/CardPackage.cs, dotnet/samples/06.auth.teamsSSO.messageExtension/Model/Package.cs, dotnet/samples/06.auth.teamsSSO.messageExtension/Program.cs, dotnet/samples/06.auth.teamsSSO.messageExtension/Properties/launchSettings.json, dotnet/samples/06.auth.teamsSSO.messageExtension/README.md, dotnet/samples/06.auth.teamsSSO.messageExtension/Resources/PackageCard.json, dotnet/samples/06.auth.teamsSSO.messageExtension/SimpleGraphClient.cs, dotnet/samples/06.auth.teamsSSO.messageExtension/Utilities.cs, dotnet/samples/06.auth.teamsSSO.messageExtension/aad.manifest.json, dotnet/samples/06.auth.teamsSSO.messageExtension/appPackage/color.png, dotnet/samples/06.auth.teamsSSO.messageExtension/appPackage/manifest.json, dotnet/samples/06.auth.teamsSSO.messageExtension/appPackage/outline.png, dotnet/samples/06.auth.teamsSSO.messageExtension/appsettings.json, dotnet/samples/06.auth.teamsSSO.messageExtension/assets/card.png, dotnet/samples/06.auth.teamsSSO.messageExtension/assets/search.png, dotnet/samples/06.auth.teamsSSO.messageExtension/env/.env.dev, dotnet/samples/06.auth.teamsSSO.messageExtension/infra/azure.bicep, dotnet/samples/06.auth.teamsSSO.messageExtension/infra/azure.parameters.json, dotnet/samples/06.auth.teamsSSO.messageExtension/infra/botRegistration/README.md, dotnet/samples/06.auth.teamsSSO.messageExtension/infra/botRegistration/azurebot.bicep, dotnet/samples/06.auth.teamsSSO.messageExtension/teamsapp.local.yml, dotnet/samples/06.auth.teamsSSO.messageExtension/teamsapp.yml, dotnet/samples/06.auth.teamsSSO.messageExtension/wwwroot/auth-end.html, dotnet/samples/06.auth.teamsSSO.messageExtension/wwwroot/auth-start.html
closes: #861
Add message extension auth example
The sample is based on latest code. So people need to provide a private build to try the sample.
=> [C#] feat: add message extension auth sample

js/samples/06.auth.oauth.adaptiveCard/README.md, js/samples/06.auth.oauth.adaptiveCard/teamsapp.local.yml, js/samples/06.auth.oauth.bot/.vscode/tasks.json, js/samples/06.auth.oauth.bot/README.md, js/samples/06.auth.oauth.bot/teamsapp.local.yml, js/samples/06.auth.oauth.messageExtension/README.md, js/samples/06.auth.oauth.messageExtension/teamsapp.local.yml
closes: #955 (issue number)
samples fixed: oauth bot, message extension & adaptive card 
- Fix readme
- remove `npm install` in the F5 flow since users will use yarn and do install & build before. Plus the re-build happens through nodemon once in debug mode.
- uncomment "Deploy" in the oauth bot.
=> [JS] chore: Fix auth sample TTK F5 flow

dotnet/samples/06.auth.teamsSSO.bot/.gitignore, dotnet/samples/06.auth.teamsSSO.bot/appsettings.Development.json, dotnet/samples/06.auth.teamsSSO.messageExtension/.gitignore, dotnet/samples/06.auth.teamsSSO.messageExtension/appsettings.Development.json
closes: #836  (issue number)
`06.auth.teamsSSO.bot` build was failing due to missing `appsettings.Development.json` file. Fixed
`06.auth.teamsSSO.messageExtension` build was failing due to missing `appsettings.Development.json` file. Fixed
=> [C#] chore: Push `appsettings` file to fix failing build

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/MessageExtensions/OAuthMessageExtensionsAuthentication.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/OAuthAuthentication.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/UserTokenClientWrapper.cs
closes: #965
Add OAuthPrompt based message extension auth
UT is blocked by not able to mock the function that acquires UserTokenClient. Did manual test against the code.
=> [C#] feat: add OAuthPrompt based message extension auth

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/TeamsSsoAuthentication.cs
closes: #1013
The application class now requires underlying implementation to throw an AuthException with invalid activity reason, throw expected exception to make the application class work as expected.
UT was blocked due to mock issue, which will be solved after GA. Manually tested the code.
=> [C#] fix: teams sso auth error with invalid activity

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/State/TempState.cs
closes: #1020
Align with JS changes to remove `History` from default temp state.
It seems there's already 0 reference on `TempState.History` so safe to remove.
- Remove `History` and `HistoryKey` from temp state
- No unit test reference
- No sample reference
=> [C#] chore: remove history from default temp state

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/ApplicationBuilderTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/Authentication/AuthenticationManagerTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/Authentication/Bot/BotAuthenticationBaseTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/Authentication/MessageExtensions/MessageExtensionsAuthenticationBaseTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/Authentication/MockedAuthentication.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/Authentication/TestAuthenticationManager.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Application.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/AuthenticationManager.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/AuthenticationOptions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/Bot/BotAuthenticationBase.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/IAuthentication.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/MessageExtensions/MessageExtensionsAuthenticationBase.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/OAuthAuthentication.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/TeamsSsoAuthentication.cs, dotnet/samples/06.auth.oauth.bot/Program.cs, dotnet/samples/06.auth.oauth.bot/README.md, dotnet/samples/06.auth.oauth.bot/infra/azure.parameters.json, dotnet/samples/06.auth.oauth.bot/infra/azure.parameters.local.json, dotnet/samples/06.auth.oauth.bot/teamsapp.local.yml, dotnet/samples/06.auth.oauth.bot/teamsapp.yml, dotnet/samples/06.auth.oauth.messageExtension/Program.cs, dotnet/samples/06.auth.teamsSSO.bot/Program.cs, dotnet/samples/06.auth.teamsSSO.messageExtension/Program.cs
closes: #1022
- Remove `isValidActivity` method for `IAuthentication` interface
- Simplify orchestrating authentication settings
- Add bash script to batch build dotnet samples.
- Support for both local and hosted library consumption.
- Fix Oauth messaging extension sample
- Suppress some sample warnings 
- Remove `Initialize()` method from `IAuthentication` interface.
- Internalize `AuthenticationOptions.Authentications` property as `_authenticationSettings`.
- Move auth initialization logic from `Application` class into `AuthenticationManager` class.
Manual testing:
- Oauth bot sample works
- I have made corresponding changes to the documentation (we use [TypeDoc](https://typedoc.org/) …
=> [C#] fix: Simply Auth interface & other fixes

dotnet/samples/06.auth.oauth.messageExtension/teamsapp.yml, dotnet/samples/06.auth.teamsSSO.bot/teamsapp.yml
closes: #1037
1. Remove project id from teamsapp.yml. Teams Toolkit will generate a new one for it so we can better distinguish different projects.
2. Fix formatting
=> [C#] chore: remove project id from teamsapp yml

.gitignore, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj, dotnet/samples/06.auth.oauth.bot/BotAuth.csproj, dotnet/samples/06.auth.oauth.messageExtension/MessageExtensionAuth.csproj
closes: #737  (issue number)
Bump .NET library to version 1.0.0
=> [C#] chore: bump .NET library to v1.0.0

js/.vscode/launch.json, js/packages/teams-ai/src/AdaptiveCards.spec.ts, js/packages/teams-ai/src/AdaptiveCards.ts, js/packages/teams-ai/src/authentication/Authentication.spec.ts, js/packages/teams-ai/src/authentication/Authentication.ts, js/packages/teams-ai/src/authentication/OAuthAdaptiveCardAuthentication.spec.ts, js/packages/teams-ai/src/authentication/OAuthBotAuthentication.spec.ts, js/packages/teams-ai/src/authentication/OAuthBotAuthentication.ts, js/packages/teams-ai/src/authentication/UserTokenAccess.spec.ts
closes: #54  (issue number)
Summary
- `src/authentication/` files coverage is above 80%
- `TeamsSsoAdaptiveCardAuthentication.ts` is an internal stub class that will be implemented very soon.
Unit tests
Other
=> [JS] chore: authentication & adaptive cards unit tests

js/packages/teams-ai/src/MemoryFork.spec.ts, js/packages/teams-ai/src/MemoryFork.ts, js/packages/teams-ai/src/TestMemoryFork.ts
closes: #1052  
Unit tests added for:
(100% coverage on % statements, branch, funcs, and lines).
=> [JS] chore: MemoryFork and TestMemoryFork unit tests 

dotnet/packages/Microsoft.TeamsAI/README.md
#minor
Creating a C# README doc equivalent to the JS README doc, but with updated C# links and language. IMPORTANT - The example/basic code under Migration section and under AI Prompt manager still needs to be changed to C# from JS. I would need Kavin or Alex to ensure this is done correctly. Alternatively, I can take this code out and just have people refer to the Migration Guide and AI Setup Guide links.
- E2E …
=> [C#] docs: Created C# README equivalent to JS README file #1057

js/packages/teams-ai/src/prompts/Message.ts, js/packages/teams-ai/src/prompts/UserInputMessage.ts
=> [JS] fix: fix type of image message

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/LLMClientTests.cs
closes: #1114
Add unit tests for `LLMClient.cs`
=> [C#] feat: LLMClient unit tests

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/OpenAIModel.cs, dotnet/samples/.workflows/build-samples.sh
closes: #1140 
This is how the OpenAI call trace logs are currently formatted:
This is how it should be:
=> [C#] fix: Calls to OpenAI trace logs format is malformed.

js/packages/teams-ai/src/authentication/UserTokenAccess.spec.ts, js/packages/teams-ai/src/prompts/DataSourceSection.spec.ts, js/packages/teams-ai/src/prompts/FunctionCallMessage.spec.ts, js/packages/teams-ai/src/prompts/FunctionResponseMessage.spec.ts
closes: #54 
- Added error test cases for `UserAccessToken`
- Added tests for `DataSourceSection`, `FunctionCallMessage`, `FunctionResponseMessage `
=> [JS] chore: UserAccessToken, DataSourceSection, FunctionCallMessage, FunctionResponseMessage Unit Tests 

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/AI.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Clients/LLMClient.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Planners/ActionPlanner.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Planners/ActionPlannerOptions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/ApplicationOptions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj
closes: #1155  (issue number)
Reason behind the bump:
- Fixed format code docs format #1055 
- Fixed package readme on nuget.org #1057 
- Fixed log format issue #1141 
=> [C#] chore: Bump dotnet library to v1.0.1

python/packages/ai/teams/ai/tokenizers/__init__.py, python/packages/ai/teams/ai/tokenizers/gpt_tokenizer.py, python/packages/ai/teams/ai/tokenizers/tokenizer.py, python/packages/ai/tests/ai/tokenizers/test_gpt_tokenizer.py
closes: #1066 
1. Implement tokenizers for Python based on the JS SDK
2. Changes the underlying coding to `cl100k_base`, which is used by gpt4 and gpt3.5. JS is using `r50k_base` and I have created https://github.com/microsoft/teams-ai/issues/1171 to track this issue.
3. Rename `GPT3Tokenizer` to `GPTTokenizer`, which seems making more sense for its functionality, as both gpt4 and gpt3.5 can use this tokenizer.
4. Add unit tests for the code
5. Add docstring for the code
- I have added tests that validates my changes, and provides …
=> [PY] feat: add tokenizer

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/LLMClientTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Clients/LLMClient.cs
closes: #1036 
- Fixed uninformative error message.
- Validated E2E through the light bot by mocking the model's response to return an invalid json object. 
=> [C#] fix: Uninformative message when max repair attempts in Action Planner 

js/packages/teams-ai/src/planners/LLMClient.ts
closes: #1036 (issue number)
- Fixed uninformative error message.
- Validated E2E through the light bot by mocking the model's response to return an invalid json object.
=> [JS] fix: Uninformative message when max repair attempts in Action Planner 

python/packages/ai/teams/ai/promptsv2/__init__.py, python/packages/ai/teams/ai/promptsv2/function_call.py, python/packages/ai/teams/ai/promptsv2/layout_engine.py, python/packages/ai/teams/ai/promptsv2/message.py, python/packages/ai/teams/ai/promptsv2/prompt_functions.py, python/packages/ai/teams/ai/promptsv2/prompt_section.py, python/packages/ai/teams/ai/promptsv2/prompt_section_base.py, python/packages/ai/teams/ai/promptsv2/prompt_section_layout.py, python/packages/ai/teams/ai/promptsv2/rendered_prompt_section.py, python/packages/ai/teams/ai/promptsv2/text_section.py, python/packages/ai/tests/ai/prompts/test_layout_engine.py, python/packages/ai/tests/ai/prompts/test_prompt_section_base.py, python/packages/ai/tests/ai/prompts/test_text_section.py
closes: #1065 
1. Implement prompt layout engine, text section as well as adding necessary data models for them
2. Add unit tests and docstring
3. Difference comparing with JS SDK: The default `text_prefix` value of `TextSection` class is changed from undefine to empty string to align with the `PromptSectionBase` class.
=> [PY] feat: python prompts layout engine

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/PromptsTests/SectionsTests/TemplateSectionTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Prompts/Sections/TemplateSection.cs
closes: #1087 (issue number)
- With this fix, starting and trailing whitespace between the "{{ }}" tags of the template syntax will be ignored, thus fixing the bug.
=> [C#] fix: template syntax whitespace bug

js/packages/teams-ai/src/prompts/TemplateSection.spec.ts, js/packages/teams-ai/src/prompts/TemplateSection.ts
closes: #1087  (issue number)
With this fix, starting and trailing whitespace between the "{{ }}" tags of the template syntax will be ignored, thus fixing the bug.
=> [JS] fix: template syntax whitespace bug

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/ApplicationRouteTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/ApplicationTests.cs
closes: #1120
Add unit tests for `Application.cs`
- Cover more branches for constructor
- Cover more branches for conversation event handler
- Add auth related tests
=> [C#] feat: Add Application unit test

python/packages/ai/teams/ai/promptsv2/__init__.py, python/packages/ai/teams/ai/promptsv2/assistant_message.py, python/packages/ai/teams/ai/promptsv2/conversation_history.py, python/packages/ai/teams/ai/promptsv2/data_source_section.py, python/packages/ai/teams/ai/promptsv2/function_call_message.py, python/packages/ai/teams/ai/promptsv2/function_response_message.py, python/packages/ai/teams/ai/promptsv2/group_section.py, python/packages/ai/teams/ai/promptsv2/system_message.py, python/packages/ai/teams/ai/promptsv2/template_section.py, python/packages/ai/teams/ai/promptsv2/user_message.py, python/packages/ai/tests/ai/prompts/test_assistant_message.py, python/packages/ai/tests/ai/prompts/test_conversation_history.py, python/packages/ai/tests/ai/prompts/test_data_source_section.py, python/packages/ai/tests/ai/prompts/test_function_call_message.py, python/packages/ai/tests/ai/prompts/test_function_response_message.py, python/packages/ai/tests/ai/prompts/test_group_section.py, python/packages/ai/tests/ai/prompts/test_system_message.py, python/packages/ai/tests/ai/prompts/test_user_message.py
closes: #1065
1. Add remaining sections and messages besides `UserInputMessage`.
=> [PY] feat: add remaining sections and messages

python/packages/ai/teams/__init__.py, python/packages/ai/teams/activity_type.py, python/packages/ai/teams/app.py, python/packages/ai/teams/message_reaction_types.py, python/packages/ai/tests/test_app.py
closes: #1292 and #1293 
- Implemented logic and tests for handling message reactions and message update events 
- Message reactions include `reactionsAdded` and `reactionsRemoved`
- Message updates include `editMessage`, `softDeleteMessage`, `undeleteMessage`
=> [PY] feat: Activity Handlers - Message Reactions and Message Update

python/packages/ai/teams/__init__.py, python/packages/ai/teams/app.py, python/packages/ai/teams/meetings.py, python/packages/ai/tests/test_meetings.py
closes: #1296
- implemented logic and tests for handling `meetingStart`, `meetingEnd` events
- implemented logic for `removeRecipientMention`
- unable to currently implement `readReceipt`, `meetingParticipantJoin`, `meetingParticipantLeave` due to missing schemas for `ReadReceiptInfo`, and `MeetingParticipantsEventDetails `classes on [botbuilder](https://learn.microsoft.com/en-us/python/api/botbuilder-schema/botbuilder.schema.teams?view=botbuilder-py-latest) 
Tracking through #1300
=> [PY] feat: Activity Handlers - Meetings and RemoveRecipientMention

js/samples/06.assistants.b.orderBot/src/index.ts
the environment variable was being loaded after importing * from bot.ts. Which means the process.env.OPENAI_KEY won't be loaded when accessed in bot.ts.
=> [JS] fix:  OPENAI_KEY not found in process.env

js/packages/teams-ai/package.json
closes: #1196
- set node engine to 16 or 18 (recommended version on [documentation](https://github.com/microsoft/teams-ai/blob/main/getting-started/QUICKSTART.md#prerequisite))
=> [JS] chore: set recommended node version

js/packages/teams-ai/package.json, js/samples/01.messaging.a.echoBot/package.json, js/samples/02.messageExtensions.a.searchCommand/package.json, js/samples/03.adaptiveCards.a.typeAheadBot/package.json, js/samples/04.ai.a.teamsChefBot/package.json, js/samples/04.ai.b.messageExtensions.AI-ME/package.json, js/samples/04.ai.c.actionMapping.lightBot/package.json, js/samples/04.ai.d.chainedActions.listBot/package.json, js/samples/04.ai.e.chainedActions.devOpsBot/package.json, js/samples/04.ai.f.vision.cardGazer/package.json, js/samples/04.ai.g.LLAMA/appPackage/build/manifest.local.json, js/samples/04.e.twentyQuestions/package.json, js/samples/05.chatModeration/package.json, js/samples/06.assistants.a.mathBot/package.json, js/samples/06.assistants.b.orderBot/package.json, js/samples/06.auth.oauth.adaptiveCard/package.json, js/samples/06.auth.oauth.bot/package.json, js/samples/06.auth.oauth.messageExtension/package.json, js/samples/06.auth.teamsSSO.bot/package.json, js/samples/06.auth.teamsSSO.messageExtension/package.json, js/samples/07.whoBot/package.json
#minor
This PR bumps the teams-ai package version to 1.1.1 and updates all samples to use the same version.
=> [JS] chore: prepare for 1.1.1 release

.github/workflows/js-build-test-lint.yml, js/packages/teams-ai/package.json, pipelines/javascript.yml
#minor
since version `16.x` is EOL https://nodejs.github.io/nodejs.dev/en/about/releases/#:~:text=Major%20Node.js%20versions%20enter%20Current%20release%20status%20for,LTS%20status%20and%20are%20ready%20for%20general%20use. we should now use >= 18.x
=> [JS] chore: update node version to LTS

js/samples/08.datasource.azureOpenAI/devTools/teamsapptester/package.json
#minor
Remove folder `devTools` from sample app, otherwise it would fail to run 'Debug in Test Tool' in Teams Toolkit with following error message:
The folder `devTools` is already included in [.gitignore](https://github.com/microsoft/teams-ai/blob/main/js/samples/08.datasource.azureOpenAI/.gitignore#L115) but was committed by accident, it's safe to remove it.
=> [JS] chore: Remove devTools folder from sample app

js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/src/cards/dynamicSearchCard.ts, js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/src/index.ts
closes: #1526
Fix 'dynamic' command of type ahead sample 
I guess technically this is a workaround, but the name of the button must match the verb's name in the card, per documentation.
- Updated card schema to 1.6 (minimum for dynamic input)
- Updated submit button name to match card id
- Add interface that matches id of card (`DynamicSelect`)
- …
=> [JS] fix: #1526: Fix typeahead sample's dynamic command

js/packages/teams-ai/src/Application.ts, js/packages/teams-ai/src/authentication/BotAuthenticationBase.spec.ts, js/packages/teams-ai/src/authentication/BotAuthenticationBase.ts, js/packages/teams-ai/src/authentication/OAuthBotAuthentication.spec.ts, js/packages/teams-ai/src/authentication/TeamsSsoBotAuthentication.spec.ts, js/packages/teams-ai/src/authentication/TeamsSsoBotAuthentication.ts
closes: #minor
#816 - keeping it open until JS/C#/PY fixes have been implemented.
A detailed description of the problem can be found in the linked issue. The solution - in simple terms - was to add the `settingName` property in the `context.activity.value` property so that the route selectors for `signin/verifyState` and `signin/tokenExchange` will trigger the correct authentication setting. 
* Added a method to populate setting name in the `context.activity.value` property.
* Updated `tokenExchangeRouteSelector` & `verifyStateRouteSelector` to check for the `settingName` in the context object.
- I have made corresponding changes to the documentation (updating the doc strings in the code …
=> [JS] fix: `signinVerify` invoke may be processed by wrong OAuth Connection

js/packages/teams-ai/src/actions/SayCommand.ts
closes: #minor
Rename `Entities` object to `AIEntity` to avoid potential collision with Bot Framework schema's `Entity`
=> [JS] refactor: Rename `Entities` interface to `AIEntity`

python/samples/04.ai.a.twentyQuestions/src/bot.py, python/samples/04.ai.b.messageExtensions.AI-ME/src/bot.py, python/samples/04.ai.c.actionMapping.lightBot/src/bot.py, python/samples/04.ai.d.chainedActions.listBot/src/bot.py, python/samples/04.ai.e.chainedActions.devOpsBot/src/bot.py, python/samples/05.chatModeration/src/bot.py
closes: #1639 
- updated path to prompts folder - previous use of `os.cwd` will use the path where its being executed (hence devs may execute from different entry points and error will be thrown when trying to access config file)
=> [PY] fix: update prompts folder path for AI samples to absolute

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Embeddings/AzureOpenAIEmbeddingsOptions.cs, js/packages/teams-ai/src/embeddings/OpenAIEmbeddings.ts, python/packages/ai/teams/ai/embeddings/azure_openai_embeddings.py, python/packages/ai/tests/ai/embeddings/test_azure_openai_embeddings.py
closes: #1688
Removed HTTPS url requirement from JS, C#, and Python.
=> [repo] fix: removed HTTPS requirement for AOAI Embeddings

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/Models/AzureSdkChatMessageExtensions.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/Models/ChatMessageExtensionsTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/Models/SequentialDelayStrategyTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/Authentication/AppConfig.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/Authentication/Bot/OAuthBotAuthenticationTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/Authentication/Bot/TeamsSsoBotAuthenticationTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/Authentication/Bot/TeamsSsoPromptTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/Authentication/MessageExtensions/TeamsSsoMessageExtensionsAuthenticationTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/Authentication/TeamsSsoAuthenticationTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/Authentication/TestAuthenticationManager.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/StateTests/TurnStateTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Planners/PredictedSayCommand.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Application.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/AdaptiveCards/AdaptiveCardsAuthenticationBase.cs
closes: #1290
- async/await on non-implemented method
- null literal assignment
- missing XML comment
- general catch
- sealed classes
=> [C#] chore: fixing check annotations

js/packages/teams-ai/src/Utilities.spec.ts, js/packages/teams-ai/src/Utilities.ts
closes: #minor
* Duplicate client citation objects were being added to the references. 
=> [JS] Fix: Duplicate client citation objects being added in activity

python/packages/ai/teams/teams_attachment_downloader/teams_attachment_downloader.py, python/packages/ai/tests/test_teams_attachment_downloader.py
closes: #1789
If download_url is available, it uses that to download the corresponding file in TeamsAttachmentDownloader. This is using the guidance here: https://devblogs.microsoft.com/microsoft365dev/working-with-files-in-your-microsoft-teams-bot/
Looks like a similar 
Looks like similar logic is in the C# codebase too: https://github.com/microsoft/teams-ai/blob/0534743ff7a65d7e8718111a53c0afee22179a4b/dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/TeamsAttachmentDownloader.cs#L83
I added a unit test and also tested it locally by sending myself a markdown file. Without this change, I got a 403 error. With this, the file was successfully downloaded.
=> [PY] fix: Use download url if possible in TeamsAttachmentDownloader

python/packages/ai/teams/ai/ai.py, python/packages/ai/teams/ai/citations/__init__.py, python/packages/ai/teams/ai/citations/citations.py, python/packages/ai/teams/teams_attachment_downloader/teams_attachment_downloader.py, python/packages/ai/tests/test_teams_attachment_downloader.py
closes: #minor
The `Activity` object onto which the citations-related fields were being added to weren't being properly deserialized into json payload.
* added `_attributes_map` which is required for `msrest.serialization` to deserialize the defined fields.
* introduced `AIEntity` which extends `Entity`, as it is in the input type to `Activity.entities`
- New and …
=> [PY] fix: Citations UI was not showing

js/packages/teams-ai/src/AI.ts, js/packages/teams-ai/src/augmentations/Augmentation.ts, js/packages/teams-ai/src/augmentations/DefaultAugmentation.spec.ts, js/packages/teams-ai/src/augmentations/DefaultAugmentation.ts, js/packages/teams-ai/src/augmentations/MonologueAugmentation.spec.ts, js/packages/teams-ai/src/augmentations/MonologueAugmentation.ts, js/packages/teams-ai/src/augmentations/SequenceAugmentation.spec.ts, js/packages/teams-ai/src/augmentations/SequenceAugmentation.ts, js/packages/teams-ai/src/internals/testing/TestModel.ts, js/packages/teams-ai/src/models/LlamaModel.ts, js/packages/teams-ai/src/models/OpenAIModel.ts, js/packages/teams-ai/src/models/PromptCompletionModel.ts, js/packages/teams-ai/src/models/TestModel.ts, js/packages/teams-ai/src/planners/ActionPlanner.ts, js/packages/teams-ai/src/planners/LLMClient.ts, js/packages/teams-ai/src/prompts/PromptManager.ts, js/packages/teams-ai/src/prompts/PromptTemplate.ts, js/packages/teams-ai/src/types/CompletionConfig.ts, js/packages/teams-ai/src/types/OpenAIFunction.ts, js/packages/teams-ai/src/types/PromptResponse.ts, js/packages/teams-ai/src/types/index.ts, js/packages/teams-ai/src/validators/ActionResponseValidator.ts, js/packages/teams-ai/src/validators/DefaultResponseValidator.ts, js/packages/teams-ai/src/validators/JSONResponseValidator.ts, js/packages/teams-ai/src/validators/PromptResponseValidator.ts
#minor
- Create `OpenAIFunction` interface
- Move `CompletionConfig` to types folder
- Add `include_tools`, `tool_choice`, and `parallel_tool_calls` to `CompletionConfig`
- Move `PromptResponses` to types folder
- Add 'tools_error' to `PromptResponseStatus`
- Update files that use the above types
- Linting cleanup of `OpenAIModel.ts`
- Linting cleanup of `AI.ts`
- New and existing unit tests pass …
=> [JS] chore: refactor and linting for CompletionConfig and PromptResponse types and files using those types

python/packages/ai/teams/auth/oauth/oauth.py
closes: # (issue number)
The OAuth get_token() function does not use the security code stored in the state param to look up the user token stored when the user signed in earlier. This results in an infinite loop of sign-in prompts when calling Auth's sign_in().
- New and existing unit tests …
=> [PY] fix: Use security code stored in state param to get user token

python/packages/ai/teams/app.py
closes: #1852
Unpacking doesn't work for array.append. Which means that for non-single files, input_files.append(*files) fails with:
`on_turn_error] unhandled error: list.append() takes exactly one argument (0 given)`
Here we append file-by-file
- New and existing unit tests pass locally …
=> [PY] fix: Remove unpacking to list for file downloads

python/packages/ai/teams/app.py
`ActivityTypes` inherits from `str` (in addition to `Enum`), so does not need to be cast to `str` before being compared to `context.activity.type`. Casting to `str` will convert a value to something like `ActivityTypes.message`, which will fail the selector comparison.
#minor
=> [PY] fix: Fix Application's activity selector to not cast ActivityTypes to str

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/OpenAIModel.cs, python/packages/ai/teams/ai/models/openai_model.py, python/packages/ai/teams/app.py
closes: #1835, #1800
- `max_input_tokens` was incorrectly passed in as openai's `max_token` (for both C# and Python)
=> [repo] fix: max_tokens bug fix in completions

python/packages/ai/.vscode/settings.json
closes: #minor
This just adds to the `.vscode/settings.json` to hopefully prevent type checking & other issues on different machines
=> [PY] fix: Add vscode python settings

js/samples/03.ai-concepts/a.twentyQuestions/.gitignore, js/samples/03.ai-concepts/a.twentyQuestions/.vscode/launch.json, js/samples/03.ai-concepts/a.twentyQuestions/.vscode/tasks.json, js/samples/03.ai-concepts/a.twentyQuestions/README.md, js/samples/03.ai-concepts/a.twentyQuestions/env/.env.testtool, js/samples/03.ai-concepts/a.twentyQuestions/package.json, js/samples/03.ai-concepts/a.twentyQuestions/teamsapp.testtool.yml
closes: #minor
Add configurations of Teams App test tool for `TwentyQuestion`
- Add **Debug in Test Tool** launch compounds and related tasks
- Add file of **.env.testtool** and **teamsapp.testtool.yml**
- Add package `env-cmd`
- Add section of **Using Teams App test tool** in **READMD.md** 
- Update **.gitignore**
=> [JS] chore: `TwentyQuestions` supports Teams App test tool

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/Bot/TeamsSsoPrompt.cs
closes: #1744
**C# fix**
Changed `DateTime.Now` to `DateTime.UtcNow` when used in the `TeamsSSOPrompt`.
**JS fix**
No bug in JS.
**PY**
TeamsSSO auth is not implemented as of now.
=> [repo] fix: TeamsSsoPrompt never completes due to timeout

python/packages/ai/teams/app.py, python/packages/ai/teams/feedback_loop_data.py, python/packages/ai/tests/test_app.py
closes: #1956
Feedback loop sends value as camelCased, not snake_cased. In this PR, we simply check for that.
https://github.com/user-attachments/assets/5710f501-10b1-45ab-999f-8aba6430e00b
❗ This fixes this issue, but the other issue is that even when i handle the feedback, I keep getting retries. Not sure what the problem is there. Edit: It looks like this is a separate issue. 
- I have added tests that validates my changes, and …
=> [PY] fix: feedback loop contract

js/samples/01.getting-started/a.echoBot/package.json, js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json, js/samples/04.ai-apps/a.teamsChefBot/package.json
=> [JS] chore: samples fix support for Teams App Test tool

js/packages/teams-ai/src/Application.ts, js/packages/teams-ai/src/StreamingResponse.spec.ts, js/packages/teams-ai/src/StreamingResponse.ts, js/packages/teams-ai/src/models/OpenAIModel.ts, js/packages/teams-ai/src/validators/ActionResponseValidator.ts, python/packages/ai/teams/app.py
closes: #2004 
- for JS/PY, the handle wrappers were missing the sendActivity call, resulting in 502s and automatic retries
- linting
=> [repo] fix: missing sendActivity invoke for file consent accept/decline handlers

getting-started/CONCEPTS/POWERED-BY-AI.md, js/package.json, js/packages/teams-ai/package.json, js/samples/01.getting-started/a.echoBot/package.json, js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json, js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json, js/samples/03.ai-concepts/a.twentyQuestions/package.json, js/samples/03.ai-concepts/b.AI-messageExtensions/package.json, js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json, js/samples/03.ai-concepts/d.chainedActions-listBot/package.json, js/samples/03.ai-concepts/e.customModel-LLAMA/package.json, js/samples/03.ai-concepts/f.chatModeration/package.json, js/samples/04.ai-apps/a.teamsChefBot/package.json, js/samples/04.ai-apps/b.devOpsBot/package.json, js/samples/04.ai-apps/c.vision-cardGazer/package.json, js/samples/04.ai-apps/d.assistants-mathBot/package.json, js/samples/04.ai-apps/e.assistants-orderBot/package.json, js/samples/04.ai-apps/f.whoBot/package.json, js/samples/04.ai-apps/g.datasource-azureAISearch/package.json, js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json, js/samples/05.authentication/a.oauth-adaptiveCard/package.json, js/samples/05.authentication/b.oauth-bot/package.json, js/samples/05.authentication/c.oauth-messageExtension/package.json, js/samples/05.authentication/d.teamsSSO-bot/package.json, js/samples/05.authentication/e.teamsSSO-messageExtension/package.json, js/yarn.lock
closes: #1947
closes #1371
- Modified package configuration for `typescript` to only allow patch updates. See Change details below for more information. This is (ideally) temporary.
- Remove `@microsoft/teamsfx` as a dependency - it turns out this dependency is entirely unused, but due to sub-dependencies was preventing us from being able to support Node >=18. Because of this and `botbuilder-js@4.23.x` now supporting node 20, teams-ai js package now also runs with node 20 too!
- Removed `browserify` - unused dependency
- Updated Powered by AI docs to slightly clarify how AI module may use a `planner`.
[TS made an update](https://devblogs.microsoft.com/typescript/announcing-typescript-5-6) that in 5.6 reveals previously 'hidden' TS errors.
`gpt-tokenizer` and `botbuilder` have  TS errors …
=> [JS] chore: dependencies cleanup: typescript, teamsfx, and browserify

python/packages/ai/teams/app.py, python/packages/ai/tests/test_app.py
closes: #1318
Added the get_token_or_sign_in_user() method. It is the interaction entrypoint for the sso authentication.
It is modeled after the JS version of this functionality. 
If the user is signed in, get the access token.
If not, triggers the sign in flow for the provided authentication setting name and returns.
In this case, the bot should end the turn until the sign in flow is completed.
- I have added tests that validates my …
=> [PY] feat: SSO - auth-sign-in

python/samples/06.auth.oauth.bot/README.md
closes: #minor
Reference: https://github.com/microsoft/teams-ai/issues/2000
Link to "other-ways-to-run-the-sample" is corrected
> Feel free to add other relevant …
=> [PY] docs: Update README.md #other-ways-to-run-the-sample

js/packages/teams-ai/src/models/OpenAIModel.ts, js/packages/teams-ai/src/prompts/PromptManager.ts, js/packages/teams-ai/src/prompts/UserInputMessage.ts, js/samples/03.ai-concepts/c.actionMapping-lightBot/src/prompts/tools/config.json, js/samples/04.ai-apps/c.vision-cardGazer/README.md, js/samples/04.ai-apps/c.vision-cardGazer/src/index.ts, js/samples/04.ai-apps/c.vision-cardGazer/src/prompts/chat/actions.json, js/samples/04.ai-apps/c.vision-cardGazer/src/prompts/chat/config.json, js/samples/04.ai-apps/c.vision-cardGazer/src/prompts/chat/skprompt.txt, js/samples/04.ai-apps/c.vision-cardGazer/teamsapp.yml, js/samples/05.authentication/b.oauth-bot/README.md, js/samples/05.authentication/b.oauth-bot/teamsapp.yml
#2039
#minor
- `OpenAIModel.ts` docstring cleanup
- `PromptManager` - change order of tools and user input
- `UserInputMessage` - don't send messages if messages are empty.
- Update cardgazer to use 4o-mini and tools augmentation
- Update CardGazer sample to improve experience.
- Add note in README for Bot SSO sample
> Feel free to add other …
=> [JS] fix: CardGazer sample

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Action/AIEntity.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Action/DefaultActions.cs, js/packages/teams-ai/src/actions/SayCommand.ts, python/packages/ai/teams/ai/ai.py, python/packages/ai/teams/ai/citations/citations.py
closes: #2064
For JS, PY, and C#: Update citations abstract to be max length 480 characters instead of 500 characters.
=> [repo] fix: JS, PY, C# - Update citations abstract length to be max 480 chars

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/StreamingResponse.cs
closes: #minor
Update to use new() for backwards compat.
=> [C#] fix: StreamingResponse array instantiation

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/AIConstants.cs, getting-started/CONCEPTS/ACTIONS.md, js/packages/teams-ai/src/AI.ts, python/packages/ai/teams/ai/actions/action_types.py
closes: #2126 
Context: https://github.com/microsoft/teams-ai/issues/2126 
Adding comments to communicate that the `StopCommand` is not compatible with the `tools` augmentation.
=> [repo] fix: add stop command docs/comments for tools augmentation compatibility

js/packages/teams-ai/src/internals/types.ts, js/packages/teams-ai/src/moderators/AzureContentSafetyModerator.spec.ts, js/packages/teams-ai/src/moderators/AzureContentSafetyModerator.ts, js/samples/03.ai-concepts/f.chatModeration/src/bot.ts, js/samples/03.ai-concepts/f.chatModeration/src/index.ts
closes: #2121 
the version of azure content safety we are using was public preview and is no longer supported, these changes update our code to work with the official GA version of content safety https://learn.microsoft.com/en-us/azure/ai-services/content-safety/how-to/migrate-to-general-availability
=> [JS] fix: content safety public preview deprecation

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Action/DefaultActions.cs, js/packages/teams-ai/package.json, js/packages/teams-ai/src/actions/SayCommand.ts, js/packages/teams-ai/src/models/OpenAIModel.spec.ts, js/packages/teams-ai/src/models/OpenAIModel.ts, js/samples/01.getting-started/a.echoBot/package.json, js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json, js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json, js/samples/03.ai-concepts/a.twentyQuestions/package.json, js/samples/03.ai-concepts/b.AI-messageExtensions/package.json, js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json, js/samples/03.ai-concepts/d.chainedActions-listBot/package.json, js/samples/03.ai-concepts/e.customModel-LLAMA/package.json, js/samples/03.ai-concepts/f.chatModeration/package.json, js/samples/04.ai-apps/a.teamsChefBot/package.json, js/samples/04.ai-apps/c.vision-cardGazer/package.json, js/samples/04.ai-apps/d.assistants-mathBot/package.json, js/samples/04.ai-apps/e.assistants-orderBot/package.json, js/samples/04.ai-apps/f.whoBot/package.json, js/samples/04.ai-apps/g.datasource-azureAISearch/package.json, js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json, js/samples/05.authentication/a.oauth-adaptiveCard/package.json, js/samples/05.authentication/b.oauth-bot/package.json, js/samples/05.authentication/c.oauth-messageExtension/package.json, js/samples/05.authentication/d.teamsSSO-bot/package.json, js/samples/05.authentication/e.teamsSSO-messageExtension/package.json, js/yarn.lock, python/packages/ai/teams/ai/ai.py
closes: #2131
closes: #2080
- Change the abstract length to 477, in the rare case where the word clips at >477 but <480, then adds ellipses
- `OpenAIModel`: re-add message context so it is not being dropped from `ToolsAugmentation` changes. This now means citations are being rendered as expected.
> Feel free to add other relevant information …
=> [JS] fix: Citations where context was being dropped in OpenAIModel.ts

js/packages/teams-ai/src/StreamingResponse.spec.ts, js/packages/teams-ai/src/StreamingResponse.ts, js/packages/teams-ai/src/models/OpenAIModel.spec.ts, js/packages/teams-ai/src/moderators/AzureContentSafetyModerator.spec.ts, js/packages/teams-ai/src/moderators/AzureContentSafetyModerator.ts, js/packages/teams-ai/src/planners/LLMClient.ts, js/packages/teams-ai/src/types/AIEntity.ts
closes: #1970
This will work slightly differently than the previous non-streaming Plan flow. Citations and its respective sensitivity labels are added per each text chunk queued. However, these will only be rendered in the final message (when the full message has been received). 
Rather than exposing the SensitivityUsageInfo object as an override on the PredictedSayCommand, the label can now be directly set as usageInfo in the AIEntity object along with the AIGenerated label and the citations.
- I have added tests that validates my changes, …
=> [JS] feat: Streaming - Citations & Sensitivity Label 

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/Models/OpenAIModelTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/OpenAIModel.cs, dotnet/samples/04.e.twentyQuestions/teamsapp.yml, dotnet/samples/08.datasource.azureopenai/teamsapp.yml
closes: #minor
The `OpenAI` sdk automatically maps the `max_tokens` configuration to the `MaxOutputTokenCount` property (i.e `max_completion_tokens`). However this does not work with Azure OpenAI service as it expects `max_tokens` for non-o1 models.
* In `OpenAIModel.cs` if the model is not in the o1 series, then use `max_tokens` field by default.
- New and existing unit tests pass locally with my …
=> [C#] fix: Map tokens config to `max_tokens` when non-o1 model is used.

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj, dotnet/samples/01.messaging.echoBot/EchoBot.csproj, dotnet/samples/02.messageExtensions.a.searchCommand/SearchCommand.csproj, dotnet/samples/03.adaptiveCards.a.typeAheadBot/TypeAheadBot.csproj, dotnet/samples/04.ai.a.teamsChefBot/TeamsChefBot.csproj, dotnet/samples/04.ai.b.messageExtensions.gptME/GPT.csproj, dotnet/samples/04.ai.c.actionMapping.lightBot/LightBot.csproj, dotnet/samples/04.ai.d.chainedActions.listBot/ListBot.csproj, dotnet/samples/04.ai.e.chainedActions.devOpsBot/DevOpsBot.csproj, dotnet/samples/04.ai.f.vision.cardMaster/CardGazer.csproj, dotnet/samples/04.ai.g.teamsChefBot-streaming/TeamsChefBot.csproj, dotnet/samples/04.e.twentyQuestions/TwentyQuestions.csproj, dotnet/samples/05.chatModeration/ChatModeration.csproj, dotnet/samples/06.assistants.a.mathBot/MathBot.csproj, dotnet/samples/06.assistants.b.orderBot/OrderBot.csproj, dotnet/samples/06.auth.oauth.bot/BotAuth.csproj, dotnet/samples/06.auth.oauth.messageExtension/MessageExtensionAuth.csproj, dotnet/samples/06.auth.teamsSSO.bot/BotAuth.csproj, dotnet/samples/06.auth.teamsSSO.messageExtension/MessageExtensionAuth.csproj, dotnet/samples/08.datasource.azureaisearch/AzureAISearchBot/AzureAISearchBot.csproj, dotnet/samples/08.datasource.azureopenai/AzureOpenAIBot.csproj
closes: #minor
* Bump `Microsoft.Teams.AI` to version 1.8.0
* Update all the samples to point to this version.
=> [C#] bump: dotnet to 1.8.0

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/StreamingResponse.cs
closes: #minor
for `entities` object, update `streamType` enum conversion to string instead of int
=> [C#] fix: update streamType enum conversion to string

js/packages/teams-ai/src/AI.ts, js/packages/teams-ai/src/Application.ts, js/packages/teams-ai/src/Messages.spec.ts, js/packages/teams-ai/src/Messages.ts, js/packages/teams-ai/src/StreamingResponse.ts, js/packages/teams-ai/src/Utilities.spec.ts, js/packages/teams-ai/src/actions/SayCommand.spec.ts, js/packages/teams-ai/src/actions/SayCommand.ts, js/packages/teams-ai/src/types/ClientCitation.ts, js/samples/03.ai-concepts/f.chatModeration/src/bot.ts, js/samples/04.ai-apps/i.teamsChefBot-streaming/src/index.ts
closes: #2167 
update types/handlers for new custom feedback loop and citations changes for ignite.
=> DO NOT MERGE [JS] feat: custom feedback form + citation changes

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Action/AIEntity.cs, js/packages/teams-ai/src/planners/AssistantsPlanner.spec.ts, js/packages/teams-ai/src/planners/AssistantsPlanner.ts, js/packages/teams-ai/src/types/ClientCitation.ts, js/samples/04.ai-apps/d.assistants-mathBot/src/bot.ts, js/samples/04.ai-apps/e.assistants-orderBot/src/bot.ts, python/packages/ai/teams/ai/citations/citations.py
closes: #2234
closes: #2233
- Fix C# `AIEntity` to make `encodingFormat` optional and not hardcoded.
- Change inline docs to indicate `encodingFormat` is for `citation.appearance.text`
- Update `AssistantsPlannerOptions` to include `api_version` field
- Update `AssistantsPlanner` to set `api_version`
=> [repo] fix: C# Citations' `encodingFormat` to not be hardcoded. Fix JS AssistantsPlanner options to set api version

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/TypingTimer.cs
closes: #minor
Fixes the issue where the typing timer is stuck after the bot sends the message.
- The send "typing" activity method is awaited to complete before the send "message" activity is processed.
=> [C#] fix: Typing indicator is "stuck"

js/package.json, js/packages/teams-ai/package.json, js/packages/teams-ai/src/planners/AssistantsPlanner.spec.ts, js/packages/teams-ai/src/planners/AssistantsPlanner.ts, js/samples/01.getting-started/a.echoBot/package.json, js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json, js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json, js/samples/03.ai-concepts/a.twentyQuestions/package.json, js/samples/03.ai-concepts/b.AI-messageExtensions/package.json, js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json, js/samples/03.ai-concepts/d.chainedActions-listBot/package.json, js/samples/03.ai-concepts/e.customModel-LLAMA/package.json, js/samples/03.ai-concepts/f.chatModeration/package.json, js/samples/04.ai-apps/a.teamsChefBot/package.json, js/samples/04.ai-apps/b.devOpsBot/package.json, js/samples/04.ai-apps/c.vision-cardGazer/package.json, js/samples/04.ai-apps/d.assistants-mathBot/package.json, js/samples/04.ai-apps/d.assistants-mathBot/src/bot.ts, js/samples/04.ai-apps/e.assistants-orderBot/package.json, js/samples/04.ai-apps/e.assistants-orderBot/src/bot.ts, js/samples/04.ai-apps/f.whoBot/package.json, js/samples/04.ai-apps/g.datasource-azureAISearch/package.json, js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json, js/samples/05.authentication/a.oauth-adaptiveCard/package.json, js/samples/05.authentication/b.oauth-bot/package.json, js/samples/05.authentication/c.oauth-messageExtension/package.json, js/samples/05.authentication/d.teamsSSO-bot/package.json, js/samples/05.authentication/e.teamsSSO-messageExtension/package.json, js/yarn.lock
closes: #2233 
- Fix error where api version was set to api_version instead of apiVersion 
- Update openai package version in all JS samples
=> [JS] fix: Assistants Planner API version

js/package.json, js/packages/teams-ai/package.json, js/samples/01.getting-started/a.echoBot/package.json, js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json, js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json, js/samples/03.ai-concepts/a.twentyQuestions/package.json, js/samples/03.ai-concepts/b.AI-messageExtensions/package.json, js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json, js/samples/03.ai-concepts/d.chainedActions-listBot/package.json, js/samples/03.ai-concepts/e.customModel-LLAMA/package.json, js/samples/03.ai-concepts/f.chatModeration/package.json, js/samples/04.ai-apps/a.teamsChefBot/package.json, js/samples/04.ai-apps/b.devOpsBot/package.json, js/samples/04.ai-apps/c.vision-cardGazer/package.json, js/samples/04.ai-apps/d.assistants-mathBot/package.json, js/samples/04.ai-apps/e.assistants-orderBot/package.json, js/samples/04.ai-apps/f.whoBot/package.json, js/samples/04.ai-apps/g.datasource-azureAISearch/package.json, js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json, js/samples/04.ai-apps/i.teamsChefBot-streaming/package.json, js/samples/05.authentication/a.oauth-adaptiveCard/package.json, js/samples/05.authentication/b.oauth-bot/package.json, js/samples/05.authentication/c.oauth-messageExtension/package.json, js/samples/05.authentication/d.teamsSSO-bot/package.json, js/samples/05.authentication/e.teamsSSO-messageExtension/package.json, js/yarn.lock
#minor
* [JS] chore: Release 1.7.0 by @corinagum in https://github.com/microsoft/teams-ai/pull/2222
* [repo] bump: (deps): Bump github/codeql-action from 3.27.5 to 3.27.6 in the production group by @dependabot in https://github.com/microsoft/teams-ai/pull/2223
* [repo] docs: Update wording in the sample readmes for clarity by @corinagum in https://github.com/microsoft/teams-ai/pull/2225
* [repo] fix: C# Citations' `encodingFormat` to not be hardcoded. Fix JS AssistantsPlanner options to set api version by @corinagum in https://github.com/microsoft/teams-ai/pull/2235
* [repo] bump: (deps): Bump github/codeql-action from 3.27.6 to 3.27.9 in the production group by @dependabot in https://github.com/microsoft/teams-ai/pull/2239
* [JS] bump: (deps-dev): Bump @microsoft/api-extractor from …
=> [JS] chore: release JS 1.7.2

js/packages/teams-ai/src/Application.ts
closes: #2285  
The stuck typing indicator appears to occur when we send a `message` activity while we're in the middle of sending a `typing` activity. The fix is to delay the outgoing `message` activity until after we finish sending the `typing` activity.
> Created a separate promise variable so that we can have two threads waiting for the same operation to complete. This lets us block the outgoing message activity until after the typing activity finishes delivering.
- I have added tests that validates my changes, and provides sufficient test …
=> [JS] fix: Fixed stuck typing indicator issue

python/packages/ai/teams/streaming/streaming_response.py
[PY] fix: StreamingResponse attributes shared between different StreamingResponse instances
closes: #2320 
Initializes `StreamingResponse` attributes for instance instead of class. Each `StreamingResponse` will handle its own attributes, hence, sequence number, queue and stream id.
```python
def __init__(self, context: TurnContext) -> None:
"""
Initializes a new instance of the `StreamingResponse` class.
:param context: The turn context.
"""
self._context = context
self._next_sequence = 1
self._stream_id = ""
self._message = ""
self._attachments = []
self._ended = False
self._citations = []
self._sensitivity_label = None
self._enable_feedback_loop = False
self._feedback_loop_type = None
self._enable_generated_by_ai_label = False
self._queue = []
self._queue_sync = None …
```
=> [PY] fix: StreamingResponse attributes shared between different StreamingResponse instances

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/OpenAIModel.cs
closes: #2298 
Fixed hyphenation fixation, added o3 support.
See Steve's PR on this issue.
=> [C#] fix: Fixed prefix check for o1 models and added o3 support

js/packages/teams-ai/src/models/OpenAIModel.ts
fixes: #2298 
We were identifying `o1` thinking models by looking for models starting with `o1-`. This is an issue on Azure OpenAI because the default deployment name is just `o1` without any dash. I removed the dash and also added support for `o3` based thinking models.  Now we special case all thinking models with an `isThinkingModel` check.
- [ x] My code follows the style guidelines of this project
- E2E testing in …
=> [JS] Bug: Fixed prefix check for `o1` models and added `o3` support

python/packages/ai/teams/state/state.py
closes: #2350
__getattr__ is only called if `__getattribute__` is not able to find the value by normal means. Python then calls __getattr__ to see if the class wants to compute the value for key. If it doesn't, it expects it to throw the attribute error (not a key error).
Currently, it's throwing a keyerror when this is the case.
See python docs here - https://docs.python.org/3/reference/datamodel.html#object.__getattr__
I essentially do what it's doing, but instead of a `KeyError` i'm reraising an `AttributeError` as python docs suggest.
- My …
=> [PY] fix: Reraise `AttributeError` from `__getattr__` if attribute is not found

README.md, book/src/developer-tools/cli/README.md, book/src/developer-tools/devtools/chat.md, book/src/getting-started/quickstart.md, book/src/welcome/README.md
#minor
Update CLI commands in documentation to use the preview version of the Teams CLI, not latest.
=> [docs] use @preview

book/src/SUMMARY.md
Remove draft for deployemets in Teams. We need to do this, but haven't yet.
=> Remove deployment draft

book/src/README.md, book/src/SUMMARY.md
if index.html isn't provided (aka a root-readme), then mdbook uses the first readme in SUMMARY.md. Thanks breaks relative links if that readme isn't at the root.
What this means is realtive links like "../foo" will break from https://microsoft.github.io/teams-ai/, but will work fine with https://microsoft.github.io/teams-ai/welcome/index.html (which is the first readme in SUMMARY.md)
=> Fix index.html

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/StreamingResponseTests.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/StreamingResponse.cs, dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Utilities/CitationUtils.cs
closes: #2461
While sending text chunks with reference to same citations, duplicate citations are added to Entities which leads to streaming errors.
For example, if citation [1] was referenced multiple times in streamed text
streamer.QueueTextChunk("This is a sample text referencing first document [1] and second document [2], However the more relevant document appears to be first document [1].");
Total 3 citations are added into the final sent activity. This leads to upstream errors and unexpected results on client.
- Adjusted citation position handling in `StreamingResponse.cs` to ensure correct alignment with text.
- Enhanced duplicate match processing in `CitationUtils.cs` using a `HashSet` to filter duplicates before citation retrieval.
- Introduced …
=> [C#] fix: Improve citation logic and tests for unique citations 

teams.md/docs/csharp/getting-started/_category_.json, teams.md/docs/typescript/essentials/_category_.json, teams.md/docs/typescript/getting-started/_category_.json, teams.md/docs/typescript/in-depth-guides/_category_.json, teams.md/docs/typescript/migrations/_category_.json
For better discoverability we want to uncollapse the first level of categories
=> Uncollapse level 1 categories

.github/workflows/deploy-teams-docs.yml, teams.md/docs/csharp/getting-started/LLMs.md, teams.md/docs/typescript/getting-started/LLMs.md, teams.md/package.json, teams.md/scripts/generate-llms-txt.js, teams.md/scripts/lib/content-processor.js, teams.md/scripts/lib/file-collector.js
LLMs txt (https://llmstxt.org/#format) is a format that's being adopted in the industry to help coding assistants leverage the library effectively. 
This PR introduces a script to generate llms.txt (small) and llms.txt (full) for both typescript and C#. In addition it generates a txt file for each document.
llms.txt (small) - this is essentially an index file that contains links to other txt files
llms.txt (full) - this is essentially a full dump of the entire documentation all concatenated together.
The files get generated when the deploy is happening. 
Also added an actual documentation to help folks discover these files.
The scripts are basically vibecoded, but I've gone through it and they seem to be correct, and doing what I want.
=> Add scripts to generate llmstxt files

js/packages/teams-ai/src/models/OpenAIModel.ts
OpenAi released gpt-5 in Aug 7, 2025. gpt-5 has deprecated the max_tokens parameter and old variable temperatures, having an api similar to the o* models. This change fixes gpt-5 usage and allows users to choose cheaper/better gpt-5 models as their base model.
Since gpt-5 models allows for tools usage and system messages but do not allow for temperature, top_p and presence_penalty parameters, a new flag has been added to toggle on just the parameters handling. This is going to fix the bad request error that happens when trying to use gpt-5 models using teams-ai
closes: #2560
Added a new isGpt5Model flag to toggle off deprecated api parameters, but keeping tool usage as system prompts.
Create a new flag variable named isGpt5Model to toggle off new max_completion_tokens and other parameters …
=> [JS] feat: #2560 Add max_completion_tokens handling for gpt-5

teams.md/docs/csharp/in-depth-guides/tabs/getting-started.md, teams.md/docs/csharp/in-depth-guides/user-authentication/quickstart.md, teams.md/docs/typescript/in-depth-guides/user-authentication/quickstart.md
In UserAuth quickstarts, the `teams new` command is missing the first param with the language
=> fix: lang to teams new command docs
