microsoft/teams-ai

js/packages/teams-ai/src/TaskModules.ts

Fix build error where variable is used before assignment

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/PromptManagerTests.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Prompt/IPromptManager.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Prompt/PromptManager.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.TeamsAI.csproj

More fixes for https://github.com/microsoft/teams-ai/issues/271
- Expose `Variables` on `IPromptManager`
- Include content files of SK to include *Tokenizers* in user/sample project

Fix IPromptManager and nupkg

---

dotnet/samples/04.e.twentyQuestions/README.md
dotnet/samples/04.e.twentyQuestions/TwentyQuestions.csproj
dotnet/samples/04.e.twentyQuestions/teamsapp.yml

- Use .NET 6.0 as described in the root README
- Tweak *Deploy to Azure* part

[C# sample] Align TwentyQuestions with other samples and readme

---

.github/workflows/dotnet-ci.yml
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.TeamsAI.csproj

add a CI step to publish dotnet package to github so it can be used via nuget

add step to publish pack to github nuget packages 

---

dotnet/samples/01.messaging.echoBot/EchoBot.csproj
dotnet/samples/01.messaging.echoBot/appsettings.Development.json

- reference TeamsAI in csproj
- add appsettings.Development.json

[C# sample]: fix missing SDK reference in echo bot

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/ResponseParserTests.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/AI.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Action/DefaultActions.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Planner/CommandJsonConverter.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Planner/PlanJsonConverter.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Planner/PredictedDoCommand.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/ResponseParser.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.TeamsAI.csproj
dotnet/samples/01.messaging.echoBot/EchoBot.csproj
dotnet/samples/02.messageExtensions.a.searchCommand/SearchCommand.csproj
dotnet/samples/03.adaptiveCards.a.typeAheadBot/TypeAheadBot.csproj
dotnet/samples/04.ai.a.teamsChefBot/TeamsChefBot.csproj
dotnet/samples/04.ai.b.messageExtensions.gptME/GPT.csproj
dotnet/samples/04.ai.c.actionMapping.lightBot/LightBot.csproj
dotnet/samples/04.e.twentyQuestions/TwentyQuestions.csproj

Fix https://github.com/microsoft/teams-ai/issues/372
- Check null or empty for `tempState.Input` and `tempState.History`
- Ignore non-Plan JSON, since adaptive card is also a JSON response. This also keeps consistency with the JS SDK.
- Fix card data in default say action.
- Update package version to release a new one. Adjust sample reference as well (`1.0.*-*` to resolve the latest version, include prerelease)

[C#] Fix issues found when porting sample

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/AzureContentSafetyClientTests.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/OpenAIClientTests.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/AzureContentSafety/AzureContentSafetyClient.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Moderator/AzureContentSafetyModerator.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Moderator/OpenAIModerator.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/OpenAI/OpenAIClient.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Utilities/DefaultHttpClient.cs

Resolve https://github.com/microsoft/teams-ai/issues/408
- Ensure singleton HttpClient in `OpenAIClient` and `AzureContentSafetyClient`
- Ensure `HttpResponseMessage` is disposed to avoid connection leak
- Add unit tests

[C#] Ensure singleton HttpClient

---

dotnet/samples/04.ai.c.actionMapping.lightBot/LightBot.csproj
dotnet/samples/04.ai.c.actionMapping.lightBot/ResponseGenerator.cs
dotnet/samples/04.ai.d.chainedActions.listBot/ListBotActions.cs
dotnet/samples/04.ai.d.chainedActions.listBot/ListBotApplication.cs
dotnet/samples/04.ai.d.chainedActions.listBot/ResponseBuilder.cs
dotnet/samples/04.ai.e.chainedActions.devOpsBot/DevOpsActions.cs
dotnet/samples/04.ai.e.chainedActions.devOpsBot/ResponseBuilder.cs
dotnet/samples/04.ai.e.chainedActions.devOpsBot/TeamsDevOpsBot.cs
dotnet/samples/04.e.twentyQuestions/ResponseBuilder.cs

A little cleanup in ListBot sample, plus fix thread-unsafe use of Random in a few other samples

Tweak a few samples

---

js/samples/03.adaptiveCards.a.typeAheadBot/README.md
js/samples/03.adaptiveCards.a.typeAheadBot/src/cards/dynamicSearchCard.ts

Fixes #297 
- Change card type to filtered
- Add information on how to interact with the bot
- Update Adaptive Card values so dynamic card doesn't say static
[sample tested with changes and it works]

Fix Adaptive Card TypeAhead sample

---

.github/pull_request_template.md
.github/workflows/dotnet-ci.yml
.github/workflows/dotnet-main.yml
.github/workflows/dotnet-pr.yml
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application.cs

closes: https://github.com/microsoft/teams-ai/issues/511
By breaking these large workflows into different modular workflows/jobs, we gain:
- update CI workflows to work concurrently
- update CI workflows to be reusable
- update CI workflows to only publish when merged to `main`
- …

[repo] fix: update dotnet workflows

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.TeamsAI.csproj
dotnet/samples/NuGet.Config

#minor
- release new version of dotnet SDK
- update nuget config

[C#] bump: release

---

.github/workflows/dotnet-build-test-lint.yml
.github/workflows/js-build-test-lint.yml

#minor
- remove C# devskim scanning in favor of codeql

[repo] chore: remove devskim in favor of codeql scanning

---

.github/workflows/pr-style.yml

#minor
Add '[repo] bump' and '[repo] Bump' as allowable PR title prefixes

[repo] chore: Add [repo] bump/Bump as PR title prefix

---

.github/dependabot.yml
.github/workflows/dependency-review.yml

#minor
- group PR's by language/package type
- add commit prefix
- add language labels

[repo] chore: customize dependabot settings

---

.github/dependabot.yml

#minor
fix dependabot configuration prefix and C# directory

[repo] chore: fix dependabot configuration

---

.github/dependabot.yml

closes: #592  (issue number)
Update dependabot to ignore version updates to major versions as it may have breaking changes.
Updated the yaml file. This will apply to .NET and JS

[repo] chore: ignore major updates

---

python/samples/echo/src/bot.py
python/samples/light/src/bot.py

closes: #612 
Enable typing for Python SDK

[PY] feat: enable typing

---

getting-started/README.md

closes #589 
Fix readme so it's in sync with the rest of the getting started docs

[repo] docs: Fix getting-started readme

---

getting-started/00.PROMPTS.md
getting-started/01.PROMPT-TEMPLATES.md
getting-started/02.PLANNER.md
getting-started/03.ACTIONS.md
getting-started/04.CHAIN.md
getting-started/05.TURNS.md
getting-started/README.md

#minor
- add python examples to docs
- change markdown `dotnet` to `C#` to fix formatting
- make all prompt examples use `prompt` format

[repo] chore: add python to docs

---

dotnet/samples/README.md

closes: #619 
Update C# sample docs to reflect updated sample set up instructions

[repo] docs: update c# samples docs

---

dotnet/samples/01.messaging.echoBot/README.md
dotnet/samples/02.messageExtensions.a.searchCommand/README.md
dotnet/samples/03.adaptiveCards.a.typeAheadBot/README.md
dotnet/samples/04.ai.a.teamsChefBot/README.md
dotnet/samples/04.ai.b.messageExtensions.gptME/README.md
dotnet/samples/04.ai.d.chainedActions.listBot/README.md
dotnet/samples/04.ai.e.chainedActions.devOpsBot/README.md
dotnet/samples/04.e.twentyQuestions/README.md
dotnet/samples/04.q.questBot/README.md
dotnet/samples/README.md

closes: #255 
Found a few docs issues in the recent samples bug bash:

[repo] docs: fix dotnet samples

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/AdaptiveCards.cs

[C#] fix: use string.Equals instead of Regex

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/ApplicationRouteTests.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/ApplicationTests.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Application.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/ConversationUpdateEvents.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/TurnEventHandler.cs

closes: #611
Implement fluent APIs in new Application class.
New APIs:
- OnActivity(string, Handler);
- OnActivity(Regex, Handler);
- OnActivity(Router, Handler);
- OnActivity(MultiRouter, Handler);
- OnConversationUpdate(string, Handler);
- OnConversationUpdate(string[], Handler);
- OnMessage(string, Handler);
- OnMessage(Regex, Handler);
- OnMessage(Router, Handler);
- OnMessage(MultiRouter, Handler);
- OnMessageReactionsAdded(Handler);
- OnMessageReactionsRemoved(Handler);
- OnBeforeTurn(Handler);
- OnAfterTurn(Handler);
- I have …

[C#] feat: Implement Application fluent API

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/MessageExtensionsTests.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/AdaptiveCards.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Application.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/MessageExtensions.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Utilities.cs

closes: #602 
Delegates:
- Task\<MessagingExtensionActionResponse> SubmitActionHandler\<TState>(ITurnContext, TState, object, CancellationToken)
- Task\<MessagingExtensionActionResponse> BotMessagePreviewEditHandler\<TState>(ITurnContext, TState, Activity, CancellationToken)
- Task BotMessagePreviewSendHandler\<TState>(ITurnContext, TState, Activity, CancellationToken)
- Task\<TaskModuleResponse> FetchTaskHandler\<TState>(ITurnContext, TState, CancellationToken)
- Task\<MessagingExtensionResult> QueryHandler\<TState>(ITurnContext, TState, Query<Dictionary<string, object>>, CancellationToken)
- Task\<MessagingExtensionResult> SelectItemHandler\<TState>(ITurnContext, TState, object, CancellationToken)
- Task\<MessagingExtensionResult> QueryLinkHandler\<TState>(ITurnContext, TState, string, …

[C#] feat: message extension fluent api

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/AdaptiveCardInvokeResponseFactory.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/AdaptiveCards.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/MessageExtensions.cs

closes: #601 #602
- add AdaptiveCardInvokeResponseFactory
- improve xml doc

[C#] refactor: add AdaptiveCardInvokeResponseFactory

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Application.cs

closes: #601 #602 
- add AdaptiveCards and MessageExtensions in Application

[C#] refactor: add AdaptiveCards and MessageExtensions in Application

---

.github/CODEOWNERS

#minor Update codeowners so PR approvals are more meaningful

[repo] chore: Update CODEOWNERS

---

getting-started/03.ACTIONS.md
js/packages/teams-ai/src/AI.ts
js/packages/teams-ai/src/AzureOpenAIModerator.spec.ts
js/packages/teams-ai/src/AzureOpenAIModerator.ts
js/packages/teams-ai/src/OpenAIModerator.spec.ts
js/packages/teams-ai/src/OpenAIModerator.ts
js/packages/teams-ai/src/OpenAIPlanner.ts
js/samples/04.ai.a.teamsChefBot/src/responseFormatter.ts
js/samples/04.ai.a.teamsChefBot/src/semanticSearch.ts
js/samples/05.chatModeration/src/bot.ts

closes: #633 
- rename action
- add moderator tests
- update docs/samples for new action name

[JS] fix: rename `RateLimitedAction` to `HttpErrorAction`

---

python/packages/ai/teams/ai/actions/action_types.py
python/packages/ai/teams/ai/ai.py
python/packages/ai/teams/ai/models/azure_openai/planner.py
python/packages/ai/teams/ai/models/openai/planner.py
python/packages/ai/tests/test_ai.py

closes: #632 
Change rate limited action to http error action
* Change rate limited action to http error action
* Add test case for the action

[PY] feat: change rate limited action to http error action

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/MessageExtensionsTests.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/InvokeActivityUtilities.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/MessageExtensions/MessageExtensions.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/MessageExtensions/MessageExtensionsHandlers.cs

closes: #713 
- composeExtension/setting
- composeExtension/querySettingUrl
- composeExtension/onCardButtonClicked

[C#] feat: handle Message Extension new activities

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Prompt/PromptResponse.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Validators/IPromptResponseValidator.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Validators/Validation.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Memory/IMemory.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Memory/Memory.cs

https://github.com/microsoft/teams-ai/issues/722
closes: #722

[C#] refactor: implement validator interface

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/PromptsTests/SectionsTests/DataSourceSectionTests.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/DataSources/IDataSource.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/DataSources/TextDataSource.cs

closes: #724 
- add `TextDataSource`
- add tests for `DataSourceSection`

[C#] feat: add DataSources

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/OpenAIEmbeddingsTests.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Embeddings/AzureOpenAIEmbeddingsOptions.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Embeddings/EmbeddingsResponse.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Embeddings/IEmbeddings.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Embeddings/OpenAIEmbeddings.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Embeddings/OpenAIEmbeddingsOptions.cs

closes: #720 
- Introduce relevant model classes for Embeddings Response (ex: EmbeddingsResponse, OpenAIEmbeddingsOptions, AzureOpenAIEmbeddingsOptions)
- Implement the main business logic to call [OpenAI Embeddings API ](https://github.com/Azure/azure-sdk-for-net/blob/5aef41fb02c7759a17f6c5e7a8c123a7120ccc00/sdk/openai/Azure.AI.OpenAI/tests/OpenAIInferenceTests.cs#L79)via Azure OpenAI SDK in OpenAIEmbeddgins.cs
- Implement unittests.
- I have made corresponding changes to the documentation (we use …

[C#] feat: Implement Embeddings and unittests

---

js/packages/teams-ai/src/AI.ts

closes: #831 
- remove schame from action entry and method parameters

[JS] fix: remove schema from AI class

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/State/ITurnState.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/State/TurnState.cs
dotnet/samples/02.messageExtensions.a.searchCommand/Program.cs

[C#] chore: update search command sample

---

dotnet/samples/03.adaptiveCards.a.typeAheadBot/Program.cs

[C#] chore: update typeahead bot

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/TestUtils/TurnStateConfig.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Planners/ActionPlanner.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Prompts/PromptManager.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Prompts/PromptManagerOptions.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/State/TurnState.cs
dotnet/samples/04.ai.b.messageExtensions.gptME/ActivityHandlers.cs
dotnet/samples/04.ai.b.messageExtensions.gptME/Model/AppState.cs
dotnet/samples/04.ai.b.messageExtensions.gptME/Program.cs
dotnet/samples/04.ai.b.messageExtensions.gptME/Prompts/Generate/config.json
dotnet/samples/04.ai.b.messageExtensions.gptME/Prompts/Update/config.json

closes: #882 
- update gpt-me sample
- fix state bugs

[C#] chore: update GPT Me Sample

---

js/packages/teams-ai/src/authentication/TeamsBotSsoPrompt.spec.ts

closes: #864 
Add UT for TeamsSsoPrompt

[JS] feat: add TeamsSsoPrompt UT

---

dotnet/samples/04.ai.c.actionMapping.lightBot/Program.cs

#minor
- update lightbot to support Azure

[C#] chore: update lightbot to support Azure

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/OpenAIModel.cs
dotnet/samples/04.ai.b.messageExtensions.gptME/Model/AppState.cs
dotnet/samples/04.ai.b.messageExtensions.gptME/Program.cs
dotnet/samples/04.ai.c.actionMapping.lightBot/Model/AppState.cs
dotnet/samples/04.ai.c.actionMapping.lightBot/Program.cs
dotnet/samples/04.ai.d.chainedActions.listBot/Model/ListState.cs
dotnet/samples/04.ai.d.chainedActions.listBot/Program.cs
dotnet/samples/04.ai.e.chainedActions.devOpsBot/Program.cs

#minor
- fix the way of specifying azure api version
- use string.IsNullOrEmpty instead of null
- use gpt-35-turbo instead of gpt-3.5-turbo for azure model
- update the way of specifying turn state

[C#] fix: fix azure api version and samples

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj

closes: #936
New version is `1.0.0-preview-2`

[C#] chore: Bump .NET library to preview-2

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj

closes: #989 (issue number)
Bump .NET library to `1.0.0-preview-3`

[C#] chore: Bump .NET library to `1.0.0-preview-3`

---

js/samples/06.auth.teamsSSO.bot/README.md
js/samples/06.auth.teamsSSO.bot/env/.env.dev
js/samples/06.auth.teamsSSO.bot/env/.env.dev.user
js/samples/06.auth.teamsSSO.bot/env/.env.local
js/samples/06.auth.teamsSSO.bot/env/.env.local.user
js/samples/06.auth.teamsSSO.bot/teamsapp.local.yml

closes: #983
1. Update readme structure to align with other samples
2. Remove step to install dependency in `teamsapp.local.yml`

[JS] docs: update 06.auth.teamsSSO.bot

---

js/samples/06.auth.teamsSSO.messageExtension/README.md
js/samples/06.auth.teamsSSO.messageExtension/env/.env.dev
js/samples/06.auth.teamsSSO.messageExtension/env/.env.dev.user
js/samples/06.auth.teamsSSO.messageExtension/env/.env.local
js/samples/06.auth.teamsSSO.messageExtension/env/.env.local.user
js/samples/06.auth.teamsSSO.messageExtension/package.json
js/samples/06.auth.teamsSSO.messageExtension/teamsapp.local.yml

closes: #984 
1. Change teams-ai dependency to remote version
2. Update wording
3. Provide differences comparing with other auth sample
4. Change link to relative path
5. Remove install dependency step from `teamsapp.local.yml`

[JS] docs: update 06.auth.teamsSSO.messageExtension setup guide

---

js/samples/04.e.twentyQuestions/teamsapp.local.yml

closes: #982  (issue number)
- Change `MicrosoftAppId` to `BOT_ID`
- Change `MicrosoftAppPassword` to `BOT_PASSWORD`

[JS] chore: Fix `twenty-questions` sample 

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj

closes: #989  (issue number)
Bump dotnet library to preview-5

[C#] chore: bump dotnet library to `preview-5`

---

js/samples/04.ai.a.teamsChefBot/teamsapp.local.yml
js/samples/04.ai.a.teamsChefBot/teamsapp.yml
js/samples/04.ai.f.vision.cardMaster/teamsapp.local.yml
js/samples/04.ai.f.vision.cardMaster/teamsapp.yml
js/samples/05.chatModeration/teamsapp.yml
js/samples/06.assistants.a.mathBot/teamsapp.yml
js/samples/06.auth.oauth.adaptiveCard/teamsapp.yml
js/samples/06.auth.teamsSSO.messageExtension/teamsapp.yml
js/samples/07.whoBot/teamsapp.yml

closes: #1037 
1. Add schema link under teamsapp.yml and teamsapp.local.yml, to provide the ability to detect syntax errors in the yaml file. It's an editor feature and won't impact how the sample runs. Some samples miss it.
2. Remove project id from teamsapp.yml. Teams Toolkit will generate a new one for it so we can better distinguish different projects.
- New and existing unit tests pass …

[JS] chore: add schema and remove project id in teamsapp yml

---

js/packages/teams-ai/package.json
js/samples/01.messaging.a.echoBot/package.json
js/samples/02.messageExtensions.a.searchCommand/package.json
js/samples/03.adaptiveCards.a.typeAheadBot/package.json
js/samples/04.ai.a.teamsChefBot/package.json
js/samples/04.ai.b.messageExtensions.AI-ME/package.json
js/samples/04.ai.d.chainedActions.listBot/package.json
js/samples/04.ai.e.chainedActions.devOpsBot/package.json
js/samples/04.ai.f.vision.cardMaster/package.json
js/samples/04.e.twentyQuestions/package.json
js/samples/05.chatModeration/package.json
js/samples/06.assistants.a.mathBot/package.json
js/samples/06.assistants.b.orderBot/package.json
js/samples/06.auth.oauth.adaptiveCard/package.json
js/samples/06.auth.oauth.bot/package.json
js/samples/06.auth.oauth.messageExtension/package.json
js/samples/06.auth.teamsSSO.bot/package.json
js/samples/06.auth.teamsSSO.messageExtension/package.json
js/samples/07.whoBot/package.json

[JS] bump: Teams-AI package for release

---

js/packages/teams-ai/README.md
js/packages/teams-ai/package.json
js/samples/01.messaging.a.echoBot/package.json
js/samples/02.messageExtensions.a.searchCommand/package.json
js/samples/03.adaptiveCards.a.typeAheadBot/package.json
js/samples/04.ai.a.teamsChefBot/package.json
js/samples/04.ai.b.messageExtensions.AI-ME/package.json
js/samples/04.ai.c.actionMapping.lightBot/package.json
js/samples/04.ai.d.chainedActions.listBot/package.json
js/samples/04.ai.e.chainedActions.devOpsBot/package.json
js/samples/04.ai.f.vision.cardMaster/package.json
js/samples/04.e.twentyQuestions/package.json
js/samples/05.chatModeration/package.json
js/samples/06.assistants.a.mathBot/package.json
js/samples/06.assistants.b.orderBot/package.json
js/samples/06.auth.oauth.adaptiveCard/package.json
js/samples/06.auth.oauth.bot/package.json
js/samples/06.auth.oauth.messageExtension/package.json
js/samples/06.auth.teamsSSO.bot/package.json
js/samples/06.auth.teamsSSO.messageExtension/package.json
js/samples/07.whoBot/package.json

[JS] docs: Update teams-AI README

---

js/packages/teams-ai/src/augmentations/DefaultAugmentation.spec.ts
js/packages/teams-ai/src/augmentations/SequenceAugmentation.spec.ts

closes: #54 
Unit tests added for:

[JS] chore: DefaultAugmentation and SequenceAugmentation unit tests 

---

js/packages/teams-ai/README.md

#minor
This has some minor fixes to the JS readme that posts to NPM JS

[JS] docs: Fixed broken link and changed naming of SDK to library.

---

README.md
getting-started/QUICKSTART.md
getting-started/README.md
getting-started/SAMPLES.md

#minor
updated the getting started README docs with minor additional details for clarity and setting customer expectations

[repo] docs: updated getting started docs for additional details

---

js/.eslintrc
js/packages/teams-ai/src/Application.spec.ts
js/packages/teams-ai/src/Application.ts
js/packages/teams-ai/src/authentication/Authentication.ts
js/samples/01.messaging.a.echoBot/.eslintrc
js/samples/02.messageExtensions.a.searchCommand/.eslintrc
js/samples/03.adaptiveCards.a.typeAheadBot/.eslintrc
js/samples/04.ai.a.teamsChefBot/.eslintrc
js/samples/04.ai.a.teamsChefBot/src/VectraDataSource.ts
js/samples/04.ai.b.messageExtensions.AI-ME/.eslintrc
js/samples/04.ai.c.actionMapping.lightBot/.eslintrc
js/samples/04.ai.d.chainedActions.listBot/.eslintrc
js/samples/04.ai.e.chainedActions.devOpsBot/.eslintrc
js/samples/04.ai.f.vision.cardMaster/.eslintrc
js/samples/04.e.twentyQuestions/.eslintrc
js/samples/05.chatModeration/.eslintrc
js/samples/06.assistants.a.mathBot/.eslintrc
js/samples/06.assistants.b.orderBot/.eslintrc
js/samples/06.auth.oauth.adaptiveCard/.eslintrc
js/samples/06.auth.oauth.bot/.eslintrc
js/samples/06.auth.oauth.messageExtension/.eslintrc
js/samples/06.auth.teamsSSO.bot/.eslintrc
js/samples/06.auth.teamsSSO.messageExtension/.eslintrc
js/samples/07.whoBot/.eslintrc

closes: #54 
- `Application.ts` unit tests (74%)
- Minor cleanup of eslint files

[JS] chore: Application unit tests

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/Augmentations/SequenceAugmentationTests.cs

closes: #1117
Add unit tests to `SequenceAugmentation`

[C#] feat: add SequenceAugmentation unit tests

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/ActionPlannerTests.cs

[C#] feat: add ActionPlanner unit test

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj
js/packages/teams-ai/package.json

[repo] chore: release `1.1.0`

---

js/packages/teams-ai/src/internals/testing/TestUtilities.ts
js/packages/teams-ai/src/prompts/UserInputMessage.spec.ts
js/packages/teams-ai/src/prompts/UserInputMessage.ts

closes: #54 
- Add unit tests for `UserInputMessage`
- Small update to `UserInputMessage` - don't add  data:etc if the image is already base64
- Update `createTestTurnContextAndState` 

[JS] chore: #54 Add unit tests for UserInputMessage

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Action/DefaultActions.cs
js/packages/teams-ai/src/AI.ts

closes: #1186 
- on default say command ensure response is present

[repo] fix: on default say action ensure command has response

---

python/packages/ai/teams/ai/promptsv2/__init__.py
python/packages/ai/teams/ai/promptsv2/completion_config.py
python/packages/ai/teams/ai/promptsv2/data_source_section.py
python/packages/ai/teams/ai/promptsv2/prompt.py
python/packages/ai/teams/ai/promptsv2/prompt_template.py
python/packages/ai/teams/ai/promptsv2/prompt_template_config.py
python/packages/ai/teams/ai/promptsv2/user_input_message.py
python/packages/ai/tests/ai/prompts/test_user_input_message.py

closes: #1065
1. Add prompt related config classes
2. Implement UserInputMessage class

[PY] feat: add prompt and user input message

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj
dotnet/samples/01.messaging.echoBot/EchoBot.csproj
dotnet/samples/02.messageExtensions.a.searchCommand/SearchCommand.csproj
dotnet/samples/03.adaptiveCards.a.typeAheadBot/TypeAheadBot.csproj
dotnet/samples/04.ai.a.teamsChefBot/TeamsChefBot.csproj
dotnet/samples/04.ai.b.messageExtensions.gptME/GPT.csproj
dotnet/samples/04.ai.c.actionMapping.lightBot/LightBot.csproj
dotnet/samples/04.ai.d.chainedActions.listBot/ListBot.csproj
dotnet/samples/04.ai.e.chainedActions.devOpsBot/DevOpsBot.csproj
dotnet/samples/04.e.twentyQuestions/TwentyQuestions.csproj
dotnet/samples/06.assistants.a.mathBot/MathBot.csproj
dotnet/samples/06.assistants.b.orderBot/OrderBot.csproj
dotnet/samples/06.auth.oauth.bot/BotAuth.csproj
dotnet/samples/06.auth.oauth.messageExtension/MessageExtensionAuth.csproj
dotnet/samples/06.auth.teamsSSO.bot/BotAuth.csproj
dotnet/samples/06.auth.teamsSSO.messageExtension/MessageExtensionAuth.csproj

closes: #1264  (issue number)
- Patch bump to release all the bug fixes so far

[C#] chore: path bump to `v1.1.1`

---

getting-started/CONCEPTS/DATA-SOURCES.md

- Fixed missing information in data sources guide

[repo] chore: Update DATA-SOURCES.md

---

python/packages/ai/poetry.lock
python/packages/ai/pyproject.toml
python/packages/ai/teams/__init__.py
python/packages/ai/teams/ai/__init__.py
python/packages/ai/teams/ai/embeddings/azure_openai_embeddings.py
python/packages/ai/teams/ai/embeddings/embeddings_model.py
python/packages/ai/teams/ai/embeddings/openai_embeddings.py
python/packages/ai/teams/ai/models/openai_model.py
python/packages/ai/teams/ai/models/prompt_completion_model.py
python/packages/ai/teams/ai/moderators/azure_content_safety_moderator.py
python/packages/ai/teams/ai/moderators/moderator.py
python/packages/ai/teams/ai/moderators/openai_moderator.py
python/packages/ai/teams/teams_adapter.py
python/packages/ai/teams/user_agent.py

closes: #1283 
Add `TeamsAdapter` for telemetry headers

[PY] feat: add `TeamsAdapter`

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/TeamsAdapter.cs
js/packages/teams-ai/package.json
js/packages/teams-ai/src/AdaptiveCards.spec.ts
js/packages/teams-ai/src/TeamsAdapter.spec.ts
js/packages/teams-ai/src/TeamsAdapter.ts

closes: #1281 
add `User-Agent` header to responses for telemetry purposes.

[repo] chore: add `User-Agent` to responses

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/ActionPlannerTests.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Planners/ActionPlanner.cs

closes: #1274 
- port missing relevant public gets

[C#] port: missing properties on ActionPlanner

---

.github/CODEOWNERS
.github/dependabot.yml

#minor
Update `CODEOWNERS` and `dependabot.yml` to include python / admins

[repo] chore: Update codeowners and dependabot.yml to include python

---

python/packages/ai/teams/adaptive_cards/__init__.py
python/packages/ai/teams/adaptive_cards/adaptive_cards.py
python/packages/ai/teams/ai/actions/action_entry.py
python/packages/ai/teams/ai/ai.py
python/packages/ai/teams/ai/prompts/prompt_manager.py
python/packages/ai/teams/app.py
python/packages/ai/teams/meetings/meetings.py
python/packages/ai/teams/message_extensions/message_extensions.py
python/packages/ai/teams/route.py
python/packages/ai/teams/state/turn_state.py
python/packages/ai/teams/task_modules/task_modules.py
python/samples/01.messaging.a.echoBot/src/api.py
python/samples/01.messaging.a.echoBot/src/bot.py

#minor
support custom `TurnState` via top level generics

[PY] fix: support custom TurnState

---

README.md
dotnet/packages/Microsoft.TeamsAI/README.md
getting-started/MIGRATION/DOTNET.md
getting-started/MIGRATION/JS.md
getting-started/MIGRATION/PYTHON.md
getting-started/MIGRATION/README.md
getting-started/QUICKSTART.md
getting-started/README.md

closes: #299 
Updating migration instructions and docs for Python, will follow up with `getting-started/CONCEPTS` after sample additions + updates are complete (#1349)

[repo] docs: updating migration and docs for python

---

js/samples/04.ai.a.teamsChefBot/README.md
js/samples/04.ai.a.teamsChefBot/assets/TeamsChef003.png

#minor
Included a new screenshot for Teams Chef Bot sample using New Teams.

[JS] chore: Add TeamsChef screenshot for new Teams

---

getting-started/CONCEPTS/ACTION-PLANNER.md
getting-started/CONCEPTS/ACTIONS.md
getting-started/CONCEPTS/APPLICATION.md
getting-started/CONCEPTS/MODERATOR.md
getting-started/CONCEPTS/PLANNER.md
getting-started/CONCEPTS/PROMPTS.md
python/packages/ai/pyproject.toml

#minor
- update getting started docs to include python code snippets
- bump python version to remove rc suffix

[PY] chore: v1 Release

---

js/samples/04.ai.a.teamsChefBot/README.md

#minor
closes: # (issue number)
Fix image display in Teams Toolkit Sample Gallery. The code change will not change README preview in Github or VSC
`![Teams Chef Bot](./assets/TeamsChef003.png)` -> `![Teams Chef Bot](./assets/TeamsChef003.png?raw=1)`
- I have added tests that validates my changes, and provides sufficient test …

[JS] chore: Update README.md image path

---

js/packages/teams-ai/package.json
js/packages/teams-ai/src/augmentations/SequenceAugmentation.ts
js/samples/04.ai.a.teamsChefBot/package.json
js/samples/04.ai.f.vision.cardGazer/package.json
js/samples/04.ai.g.LLAMA/src/index.ts
js/samples/05.chatModeration/package.json
js/samples/06.assistants.a.mathBot/package.json
js/samples/06.assistants.b.orderBot/package.json
js/samples/08.datasource.azureAISearch/package.json
js/yarn.lock

#minor
- Bump axios 
- Bump @microsoft/teams-fx
- Lint fix

[JS] bump: Manual bump of axios and @microsoft/teamsfx

---

js/samples/04.ai.a.teamsChefBot/teamsapp.yml
js/samples/08.datasource.azureAISearch/teamsapp.yml

closes: #minor
* `teamsapp.yml` file was breaking for the chefbot & azure ai search bot. Updated and did test deployment.

[JS] fix: Broken teamsapp.yml files

---

js/samples/04.ai.e.chainedActions.devOpsBot/package.json

#minor
1) Added types for jsonwebtoken as it would generate TS issues when building the app. 
2) Also added an entry for openai v4.28 as it's required by the teams-ai module.

[JS] chore: add packages for devOps sample

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj

closes: #minor
* Patch bump dotnet library to version `1.1.3`

[C#] bump: to version `1.1.3`

---

js/samples/04.ai.a.teamsChefBot/package.json

[JS] fix: package.json error in TeamsChefBot

---

js/packages/teams-ai/package.json
js/samples/01.getting-started/a.echoBot/package.json
js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json
js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json
js/samples/04.ai.a.teamsChefBot/package.json
js/samples/04.ai.b.messageExtensions.AI-ME/package.json
js/samples/04.ai.c.actionMapping.lightBot/package.json
js/samples/04.ai.d.chainedActions.listBot/package.json
js/samples/04.ai.e.chainedActions.devOpsBot/package.json
js/samples/04.ai.f.vision.cardGazer/package.json
js/samples/04.e.twentyQuestions/package.json
js/samples/05.chatModeration/package.json
js/samples/06.assistants.a.mathBot/package.json
js/samples/06.assistants.b.orderBot/package.json
js/samples/06.auth.oauth.adaptiveCard/package.json
js/samples/06.auth.oauth.bot/package.json
js/samples/06.auth.oauth.messageExtension/package.json
js/samples/06.auth.teamsSSO.bot/package.json
js/samples/06.auth.teamsSSO.messageExtension/package.json
js/samples/07.whoBot/package.json
js/samples/08.datasource.azureOpenAI/package.json
js/yarn.lock

[JS] chore: Patch js package and its samples

---

js/packages/teams-ai/src/embeddings/OpenAIEmbeddings.ts
js/packages/teams-ai/src/internals/types.ts
js/packages/teams-ai/src/models/OpenAIModel.ts

closes: #1201 
These changes update the `OpenAIModel` and `OpenAIEmbeddings` classes to support recent parameter changes by OpenAI. They also add support for calling other OpenAI compliant services like [LLaMA.cpp](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md).
- Added new `OpenAILikeModelOptions` interface and updated `OpenAIModel` class to conditionally send an Authorization header to the model server.
- Updated `BaseOpenAIModelOptions` interface and `OpenAIModel` class to support OpenAI's `response_format` parameter.
- Updated `BaseOpenAIModelOptions` interface and `OpenAIModel` class to support OpenAI's `seed` parameter.
- Added new `OpenAILikeEmbeddingOptions` interface and updated `OpenAIEmbeddingl` class to conditionally send an Authorization header …

[JS] feat: Updates to OpenAIModel and OpenAIEmbeddings classes.

---

js/samples/README.md

fixes #1553 
update document 
Add document about deploying Bot to Linux Web App

[JS] docs: Add document about deploying Bot to Linux Web App

---

dotnet/samples/08.datasource.azureaisearch/AzureAISearchBot/teamsapp.yml
js/samples/03.ai-concepts/e.customModel-LLAMA/teamsapp.yml

[JS] fix: remove projectId in teasmfx yml file

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/Application/ApplicationRouteTests.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Application.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/HandoffHandler.cs
js/packages/teams-ai/src/Application.spec.ts
js/packages/teams-ai/src/Application.ts
js/packages/teams-ai/src/embeddings/OpenAIEmbeddings.ts
js/packages/teams-ai/src/models/OpenAIModel.ts
js/yarn.lock
python/packages/ai/teams/app.py
python/packages/ai/tests/test_app.py
python/packages/ai/tests/test_teams_attachment_downloader.py

#minor
#1447 
add activity handler for handoffs

[JS] feat: handoff activity handler

---

js/packages/teams-ai/README.md

Updating the python support in our repo
closes: #minor

[PY] chore: Update README.md with python details

---

js/packages/teams-ai/src/actions/SayCommand.ts

[JS] fix: #1617 Update SayCommand to use correct text for referencedCitations

---

getting-started/CONCEPTS/POWERED-BY-AI.md

#minor
Update powered by AI docs

[repo] docs: Update POWERED-BY-AI.md

---

.github/ISSUE_TEMPLATE/developer-support.md

[repo] chore: Add dev support to issues template

---

js/packages/teams-ai/package.json
js/samples/01.getting-started/a.echoBot/package.json
js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json
js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json
js/samples/03.ai-concepts/a.twentyQuestions/package.json
js/samples/03.ai-concepts/b.AI-messageExtensions/package.json
js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json
js/samples/03.ai-concepts/d.chainedActions-listBot/package.json
js/samples/03.ai-concepts/e.customModel-LLAMA/package.json
js/samples/03.ai-concepts/f.chatModeration/package.json
js/samples/04.ai-apps/a.teamsChefBot/package.json
js/samples/04.ai-apps/b.devOpsBot/package.json
js/samples/04.ai-apps/c.vision-cardGazer/package.json
js/samples/04.ai-apps/d.assistants-mathBot/package.json
js/samples/04.ai-apps/e.assistants-orderBot/package.json
js/samples/04.ai-apps/f.whoBot/package.json
js/samples/04.ai-apps/g.datasource-azureAISearch/package.json
js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json
js/samples/05.authentication/a.oauth-adaptiveCard/package.json
js/samples/05.authentication/b.oauth-bot/package.json
js/samples/05.authentication/c.oauth-messageExtension/package.json
js/samples/05.authentication/d.teamsSSO-bot/package.json
js/samples/05.authentication/e.teamsSSO-messageExtension/package.json

[JS] chore: Release js 1.2.0

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj
dotnet/samples/01.messaging.echoBot/EchoBot.csproj
dotnet/samples/02.messageExtensions.a.searchCommand/SearchCommand.csproj
dotnet/samples/03.adaptiveCards.a.typeAheadBot/TypeAheadBot.csproj
dotnet/samples/04.ai.a.teamsChefBot/TeamsChefBot.csproj
dotnet/samples/04.ai.b.messageExtensions.gptME/GPT.csproj
dotnet/samples/04.ai.c.actionMapping.lightBot/LightBot.csproj
dotnet/samples/04.ai.d.chainedActions.listBot/ListBot.csproj
dotnet/samples/04.ai.e.chainedActions.devOpsBot/DevOpsBot.csproj
dotnet/samples/04.e.twentyQuestions/TwentyQuestions.csproj
dotnet/samples/06.assistants.a.mathBot/MathBot.csproj
dotnet/samples/06.assistants.b.orderBot/OrderBot.csproj
dotnet/samples/06.auth.oauth.bot/BotAuth.csproj
dotnet/samples/06.auth.oauth.messageExtension/MessageExtensionAuth.csproj
dotnet/samples/06.auth.teamsSSO.bot/BotAuth.csproj
dotnet/samples/06.auth.teamsSSO.messageExtension/MessageExtensionAuth.csproj
dotnet/samples/08.datasource.azureaisearch/AzureAISearchBot/AzureAISearchBot.csproj
dotnet/samples/08.datasource.azureopenai/AzureOpenAIBot.csproj

[C#] bump: to version 1.2.0

---

js/samples/04.ai-apps/h.datasource-azureOpenAI/README.md

[JS] chore: Update README.md in datasource AzureOpenAI

---

js/packages/teams-ai/src/planners/AssistantsPlanner.spec.ts
js/packages/teams-ai/src/planners/AssistantsPlanner.ts

#minor
https://github.com/microsoft/teams-ai/issues/1590
ensure plan generated by assistants planner maps to message with citations properly.

[JS] fix: map assitants response to citations

---

js/packages/teams-ai/package.json
js/samples/01.getting-started/a.echoBot/package.json
js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json
js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json
js/samples/03.ai-concepts/a.twentyQuestions/package.json
js/samples/03.ai-concepts/b.AI-messageExtensions/package.json
js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json
js/samples/03.ai-concepts/d.chainedActions-listBot/package.json
js/samples/03.ai-concepts/e.customModel-LLAMA/package.json
js/samples/03.ai-concepts/f.chatModeration/package.json
js/samples/04.ai-apps/a.teamsChefBot/package.json
js/samples/04.ai-apps/b.devOpsBot/package.json
js/samples/04.ai-apps/c.vision-cardGazer/package.json
js/samples/04.ai-apps/d.assistants-mathBot/package.json
js/samples/04.ai-apps/e.assistants-orderBot/package.json
js/samples/04.ai-apps/f.whoBot/package.json
js/samples/04.ai-apps/g.datasource-azureAISearch/package.json
js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json
js/samples/04.ai-apps/h.datasource-azureOpenAI/src/app.ts
js/samples/05.authentication/a.oauth-adaptiveCard/package.json
js/samples/05.authentication/b.oauth-bot/package.json
js/samples/05.authentication/c.oauth-messageExtension/package.json
js/samples/05.authentication/d.teamsSSO-bot/package.json
js/samples/05.authentication/e.teamsSSO-messageExtension/package.json

[JS] chore: Patch release 1.2.1

---

python/packages/ai/teams/state/state.py
python/packages/ai/teams/state/todict.py
python/samples/04.ai.c.actionMapping.lightBot/src/bot.py

[PY] fix: ensure state saves and loads properly

---

README.md

[repo] chore: Update README.md

---

python/packages/ai/teams/ai/augmentations/sequence_augmentation.py
python/packages/ai/teams/utils/to_string.py
python/packages/ai/tests/ai/augmentations/test_sequence_augmentation.py
python/packages/ai/tests/ai/prompts/test_conversation_history.py
python/packages/ai/tests/ai/prompts/test_function_response_message.py
python/packages/ai/tests/ai/prompts/test_template_section.py
python/packages/ai/tests/utils/test_to_string.py

[PY] fix: Update commands validation for sequence augmentation

---

js/packages/teams-ai/package.json
js/samples/01.getting-started/a.echoBot/package.json
js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json
js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json
js/samples/03.ai-concepts/a.twentyQuestions/package.json
js/samples/03.ai-concepts/b.AI-messageExtensions/package.json
js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json
js/samples/03.ai-concepts/d.chainedActions-listBot/package.json
js/samples/03.ai-concepts/e.customModel-LLAMA/package.json
js/samples/03.ai-concepts/f.chatModeration/package.json
js/samples/04.ai-apps/a.teamsChefBot/package.json
js/samples/04.ai-apps/b.devOpsBot/package.json
js/samples/04.ai-apps/c.vision-cardGazer/package.json
js/samples/04.ai-apps/d.assistants-mathBot/package.json
js/samples/04.ai-apps/e.assistants-orderBot/package.json
js/samples/04.ai-apps/f.whoBot/package.json
js/samples/04.ai-apps/g.datasource-azureAISearch/package.json
js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json
js/samples/05.authentication/a.oauth-adaptiveCard/package.json
js/samples/05.authentication/b.oauth-bot/package.json
js/samples/05.authentication/c.oauth-messageExtension/package.json
js/samples/05.authentication/d.teamsSSO-bot/package.json
js/samples/05.authentication/e.teamsSSO-messageExtension/package.json

[JS] chore: 1.3.0 release

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Planners/PredictedSayCommand.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj
dotnet/samples/01.messaging.echoBot/EchoBot.csproj
dotnet/samples/02.messageExtensions.a.searchCommand/SearchCommand.csproj
dotnet/samples/03.adaptiveCards.a.typeAheadBot/TypeAheadBot.csproj
dotnet/samples/04.ai.a.teamsChefBot/TeamsChefBot.csproj
dotnet/samples/04.ai.b.messageExtensions.gptME/ActivityHandlers.cs
dotnet/samples/04.ai.b.messageExtensions.gptME/GPT.csproj
dotnet/samples/04.ai.c.actionMapping.lightBot/LightBot.csproj
dotnet/samples/04.ai.d.chainedActions.listBot/ListBot.csproj
dotnet/samples/04.ai.e.chainedActions.devOpsBot/DevOpsBot.csproj
dotnet/samples/04.ai.f.vision.cardMaster/CardGazer.csproj
dotnet/samples/04.e.twentyQuestions/GameBotHandlers.cs
dotnet/samples/04.e.twentyQuestions/TwentyQuestions.csproj
dotnet/samples/06.assistants.a.mathBot/MathBot.csproj
dotnet/samples/06.assistants.b.orderBot/OrderBot.csproj
dotnet/samples/06.auth.oauth.bot/BotAuth.csproj
dotnet/samples/06.auth.oauth.messageExtension/MessageExtensionAuth.csproj
dotnet/samples/06.auth.teamsSSO.bot/BotAuth.csproj
dotnet/samples/06.auth.teamsSSO.messageExtension/MessageExtensionAuth.csproj
dotnet/samples/08.datasource.azureaisearch/AzureAISearchBot/AzureAISearchBot.csproj
dotnet/samples/08.datasource.azureopenai/AzureOpenAIBot.csproj
dotnet/samples/08.datasource.azureopenai/ResponseCardCreator.cs

closes: #minor
Updated samples to reference v1.4.0 and fixed failing builds.

[repo] bump: dotnet to v1.3.0

---

js/packages/teams-ai/package.json
js/samples/01.getting-started/a.echoBot/package.json
js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json
js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json
js/samples/03.ai-concepts/a.twentyQuestions/package.json
js/samples/03.ai-concepts/b.AI-messageExtensions/package.json
js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json
js/samples/03.ai-concepts/d.chainedActions-listBot/package.json
js/samples/03.ai-concepts/e.customModel-LLAMA/package.json
js/samples/03.ai-concepts/f.chatModeration/package.json
js/samples/04.ai-apps/a.teamsChefBot/package.json
js/samples/04.ai-apps/b.devOpsBot/package.json
js/samples/04.ai-apps/c.vision-cardGazer/package.json
js/samples/04.ai-apps/d.assistants-mathBot/package.json
js/samples/04.ai-apps/e.assistants-orderBot/package.json
js/samples/04.ai-apps/f.whoBot/package.json
js/samples/04.ai-apps/g.datasource-azureAISearch/package.json
js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json
js/samples/05.authentication/a.oauth-adaptiveCard/package.json
js/samples/05.authentication/b.oauth-bot/package.json
js/samples/05.authentication/c.oauth-messageExtension/package.json
js/samples/05.authentication/d.teamsSSO-bot/package.json
js/samples/05.authentication/e.teamsSSO-messageExtension/package.json

[JS] Bump to 1.3.1

---

js/packages/teams-ai/README.md

#minor
Minor fix to JS readme (what is seen on npmjs)

[JS] fix: Update js teams-ai README.md

---

js/packages/teams-ai/src/AI.ts

closes: #1782
Removing unused field from streaming implementation

[JS] chore: Remove unused BeforeStreamActionName

---

python/packages/ai/README.md

[repo] chore: Update README.md to fix link to migration guide

---

python/packages/ai/teams/app.py

closes: #1770 
- fixed double nesting of List

[PY] fix: typing for input_file

---

python/samples/04.ai.g.autogen.product-spec-critique/README.md

#minor
- general update to autogen sample README to match other samples

[PY] chore: updated README for autogen sample

---

python/packages/ai/teams/auth/oauth/oauth.py

[PY] fix: Perform type check before getting state from value

---

js/samples/05.authentication/d.teamsSSO-bot/README.md

closes: #minor
Add instructions for how to update `teamsSSO-bot` to enable multi-tenant auth.

[JS] chore: Add instructions for configuring multi-tenant auth in teamsSso-bot sample.

---

python/packages/ai/poetry.lock
python/packages/ai/pyproject.toml

[PY] chore: minor bump to 1.3.0

---

js/samples/04.ai-apps/h.datasource-azureOpenAI/README.md

#minor
Updated README to for updated deployment instructions on assigning cognitive services openai user role after the bot resources are deployed to azure.

[JS] docs: Updated README to for updated deployment instructions

---

js/samples/04.ai-apps/c.vision-cardGazer/teamsapp.yml

Fixed bot name
closes: #minor
Fixed bot name in teamsapp.yml to be consistent with teamsapp.local.yml
Changed 
```name: TeamsChef${{APP_NAME_SUFFIX}}```
to 
``` name: CardGazer${{APP_NAME_SUFFIX}}```
**code snippets**: 
> Feel free to add other …

[JS] fix: Update teamsapp.yml

---

python/packages/ai/teams/app.py
python/packages/ai/tests/test_app.py

closes: #minor
- changes discussed in #1892

[PY] fix: feedback loop handler - dict access

---

python/packages/ai/teams/app.py
python/packages/ai/teams/feedback_loop_data.py

[PY] fix: empty payload expected by SMBA for feedback loop activity

---

python/packages/ai/pyproject.toml

[PY] chore: minor bump to 1.4.0

---

js/packages/teams-ai/package.json
js/samples/01.getting-started/a.echoBot/package.json
js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json
js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json
js/samples/03.ai-concepts/a.twentyQuestions/package.json
js/samples/03.ai-concepts/b.AI-messageExtensions/package.json
js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json
js/samples/03.ai-concepts/d.chainedActions-listBot/package.json
js/samples/03.ai-concepts/e.customModel-LLAMA/package.json
js/samples/03.ai-concepts/f.chatModeration/package.json
js/samples/04.ai-apps/a.teamsChefBot/package.json
js/samples/04.ai-apps/b.devOpsBot/package.json
js/samples/04.ai-apps/c.vision-cardGazer/package.json
js/samples/04.ai-apps/d.assistants-mathBot/package.json
js/samples/04.ai-apps/e.assistants-orderBot/package.json
js/samples/04.ai-apps/f.whoBot/package.json
js/samples/04.ai-apps/g.datasource-azureAISearch/package.json
js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json
js/samples/05.authentication/a.oauth-adaptiveCard/package.json
js/samples/05.authentication/b.oauth-bot/package.json
js/samples/05.authentication/c.oauth-messageExtension/package.json
js/samples/05.authentication/d.teamsSSO-bot/package.json
js/samples/05.authentication/e.teamsSSO-messageExtension/package.json
js/yarn.lock

[JS] chore: release v1.4.0

---

getting-started/MIGRATION/01.JS.md
getting-started/MIGRATION/02.DOTNET.md
getting-started/MIGRATION/03.PYTHON.md

[repo] docs: Add missing Conversation Update Events

---

getting-started/CONCEPTS/PROMPTS.md

[repo] docs: Fix the way the beforeTurn event is registered in JS

---

js/samples/04.ai-apps/b.devOpsBot/package.json

[JS] fix: Fix openai version for devOpsBot

---

CONTRIBUTING.md

Remove dead links in legal section
closes: #2033

[repo] chore: Update CONTRIBUTING.md

---

js/samples/04.ai-apps/i.teamsChefBot-streaming/README.md

closes: #minor
Updated ChefBot sample instructions for streaming. 

[repo] chore: update README for streaming

---

js/packages/teams-ai/package.json
js/samples/01.getting-started/a.echoBot/package.json
js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json
js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json
js/samples/03.ai-concepts/a.twentyQuestions/package.json
js/samples/03.ai-concepts/b.AI-messageExtensions/package.json
js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json
js/samples/03.ai-concepts/d.chainedActions-listBot/package.json
js/samples/03.ai-concepts/e.customModel-LLAMA/package.json
js/samples/03.ai-concepts/f.chatModeration/package.json
js/samples/04.ai-apps/a.teamsChefBot/package.json
js/samples/04.ai-apps/b.devOpsBot/package.json
js/samples/04.ai-apps/c.vision-cardGazer/package.json
js/samples/04.ai-apps/d.assistants-mathBot/package.json
js/samples/04.ai-apps/e.assistants-orderBot/package.json
js/samples/04.ai-apps/f.whoBot/package.json
js/samples/04.ai-apps/g.datasource-azureAISearch/package.json
js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json
js/samples/04.ai-apps/i.teamsChefBot-streaming/package.json
js/samples/05.authentication/a.oauth-adaptiveCard/package.json
js/samples/05.authentication/b.oauth-bot/package.json
js/samples/05.authentication/c.oauth-messageExtension/package.json
js/samples/05.authentication/d.teamsSSO-bot/package.json
js/samples/05.authentication/e.teamsSSO-messageExtension/package.json
js/yarn.lock

[JS] chore: bump packages

---

python/samples/04.ai.f.dataSource.azureOpenAI/README.md

closes: #minor
Reference: https://github.com/microsoft/teams-ai/issues/2000
Link to Azure OpenAI On Your Data is corrected
> Feel free to add other relevant …

[PY] docs: Update README.md

---

python/samples/06.auth.oauth.messageExtensions/README.md

closes: #minor
Reference: https://github.com/microsoft/teams-ai/issues/2000
Link to "other-ways-to-run-the-sample" is corrected
> Feel free to add other relevant …

[PY] docs: Update README.md #other-ways-to-run-the-sample

---

getting-started/CONCEPTS/POWERED-BY-AI.md

closes: https://github.com/owner/repo/issues/2061
Python feedback loop syntax correction from  @app.feedback_loop to  @app.feedback_loop()

[repo] docs: Update POWERED-BY-AI.md syntax correction

---

python/packages/ai/pyproject.toml

[PY] bump: 1.4.1 patch

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj
dotnet/samples/01.messaging.echoBot/EchoBot.csproj
dotnet/samples/02.messageExtensions.a.searchCommand/SearchCommand.csproj
dotnet/samples/03.adaptiveCards.a.typeAheadBot/TypeAheadBot.csproj
dotnet/samples/04.ai.a.teamsChefBot/TeamsChefBot.csproj
dotnet/samples/04.ai.b.messageExtensions.gptME/GPT.csproj
dotnet/samples/04.ai.c.actionMapping.lightBot/LightBot.csproj
dotnet/samples/04.ai.d.chainedActions.listBot/ListBot.csproj
dotnet/samples/04.ai.e.chainedActions.devOpsBot/DevOpsBot.csproj
dotnet/samples/04.ai.f.vision.cardMaster/CardGazer.csproj
dotnet/samples/04.e.twentyQuestions/TwentyQuestions.csproj
dotnet/samples/06.assistants.a.mathBot/MathBot.csproj
dotnet/samples/06.assistants.b.orderBot/OrderBot.csproj
dotnet/samples/06.auth.oauth.bot/BotAuth.csproj
dotnet/samples/06.auth.oauth.messageExtension/MessageExtensionAuth.csproj
dotnet/samples/06.auth.teamsSSO.bot/BotAuth.csproj
dotnet/samples/06.auth.teamsSSO.messageExtension/MessageExtensionAuth.csproj
dotnet/samples/08.datasource.azureaisearch/AzureAISearchBot/AzureAISearchBot.csproj
dotnet/samples/08.datasource.azureopenai/AzureOpenAIBot.csproj

* Bumped `Microsoft.Teams.AI` to version 1.7.0 and updated all the samples.

[C#] bump: dotnet to 1.7.0

---

dotnet/samples/04.ai.a.teamsChefBot/files/c#-migration.txt
dotnet/samples/04.ai.g.teamsChefBot-streaming/files/c#-migration.txt
getting-started/CONCEPTS/USER-AUTH.md
getting-started/MIGRATION/02.DOTNET.md
js/packages/teams-ai/src/AdaptiveCards.spec.ts
js/packages/teams-ai/src/authentication/Authentication.spec.ts
js/packages/teams-ai/src/authentication/Authentication.ts
js/packages/teams-ai/src/authentication/OAuthBotAuthentication.spec.ts

#minor
Just a typo correction.
(see: https://prowritingaid.com/comming-or-coming)

[repo] docs: fix typo

---

README.md

#minor Corrected "are" to "is" in [README.md].
This pull request addresses a minor typo found in the repository. The typo has been corrected to improve clarity and maintain the quality of the documentation.
This change is purely cosmetic and does not affect functionality.
closes: # (issue number)
- I have added tests that validates …

[repo] docs: Update README.md fixed a typo

---

js/packages/teams-ai/package.json
js/samples/01.getting-started/a.echoBot/package.json
js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json
js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json
js/samples/03.ai-concepts/a.twentyQuestions/package.json
js/samples/03.ai-concepts/b.AI-messageExtensions/package.json
js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json
js/samples/03.ai-concepts/d.chainedActions-listBot/package.json
js/samples/03.ai-concepts/e.customModel-LLAMA/package.json
js/samples/03.ai-concepts/f.chatModeration/package.json
js/samples/04.ai-apps/a.teamsChefBot/package.json
js/samples/04.ai-apps/b.devOpsBot/package.json
js/samples/04.ai-apps/c.vision-cardGazer/package.json
js/samples/04.ai-apps/d.assistants-mathBot/package.json
js/samples/04.ai-apps/e.assistants-orderBot/package.json
js/samples/04.ai-apps/f.whoBot/package.json
js/samples/04.ai-apps/g.datasource-azureAISearch/package.json
js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json
js/samples/04.ai-apps/i.teamsChefBot-streaming/package.json
js/samples/05.authentication/a.oauth-adaptiveCard/package.json
js/samples/05.authentication/b.oauth-bot/package.json
js/samples/05.authentication/c.oauth-messageExtension/package.json
js/samples/05.authentication/d.teamsSSO-bot/package.json
js/samples/05.authentication/e.teamsSSO-messageExtension/package.json

#minor
Bump teams-ai package in samples and src package for patch release.

[JS] chore: Bump Teams-AI package for patch release

---

js/package.json
js/packages/teams-ai/package.json
js/samples/01.getting-started/a.echoBot/package.json
js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json
js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json
js/samples/03.ai-concepts/a.twentyQuestions/package.json
js/samples/03.ai-concepts/b.AI-messageExtensions/package.json
js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json
js/samples/03.ai-concepts/d.chainedActions-listBot/package.json
js/samples/03.ai-concepts/e.customModel-LLAMA/package.json
js/samples/03.ai-concepts/f.chatModeration/package.json
js/samples/04.ai-apps/a.teamsChefBot/package.json
js/samples/04.ai-apps/b.devOpsBot/package.json
js/samples/04.ai-apps/c.vision-cardGazer/package.json
js/samples/04.ai-apps/d.assistants-mathBot/package.json
js/samples/04.ai-apps/e.assistants-orderBot/package.json
js/samples/04.ai-apps/f.whoBot/package.json
js/samples/04.ai-apps/g.datasource-azureAISearch/package.json
js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json
js/samples/04.ai-apps/i.teamsChefBot-streaming/package.json
js/samples/05.authentication/a.oauth-adaptiveCard/package.json
js/samples/05.authentication/b.oauth-bot/package.json
js/samples/05.authentication/c.oauth-messageExtension/package.json
js/samples/05.authentication/d.teamsSSO-bot/package.json
js/samples/05.authentication/e.teamsSSO-messageExtension/package.json
js/yarn.lock

#minor
Bump packages for patch release 1.5.3

[JS] chore: patch release v 1.5.3

---

python/packages/ai/pyproject.toml
python/packages/ai/teams/ai/planners/assistants_planner.py
python/packages/ai/tests/ai/models/test_openai_model.py
python/packages/ai/tests/ai/planners/test_assistants_planner.py
python/samples/01.messaging.a.echoBot/pyproject.toml
python/samples/02.messageExtensions.a.searchCommand/pyproject.toml
python/samples/03.adaptiveCards.a.typeAheadBot/pyproject.toml
python/samples/04.ai.a.twentyQuestions/pyproject.toml
python/samples/04.ai.b.messageExtensions.AI-ME/pyproject.toml
python/samples/04.ai.c.actionMapping.lightBot/pyproject.toml
python/samples/04.ai.d.chainedActions.listBot/pyproject.toml
python/samples/04.ai.e.chainedActions.devOpsBot/pyproject.toml
python/samples/04.ai.f.dataSource.azureOpenAI/pyproject.toml
python/samples/04.ai.g.autogen.product-spec-critique/pyproject.toml
python/samples/04.ai.h.chainedActions.listBot-streaming/pyproject.toml
python/samples/05.chatModeration/pyproject.toml
python/samples/06.assistants.a.mathBot/pyproject.toml
python/samples/06.assistants.b.orderBot/pyproject.toml
python/samples/06.auth.oauth.bot/pyproject.toml
python/samples/06.auth.oauth.messageExtensions/pyproject.toml
python/samples/07.planners.a.langchain/pyproject.toml

closes: #minor
- Package update and sample updates

[PY] bump: minor bump to 1.5.0

---

js/packages/teams-ai/package.json
js/samples/01.getting-started/a.echoBot/package.json
js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json
js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json
js/samples/03.ai-concepts/a.twentyQuestions/package.json
js/samples/03.ai-concepts/b.AI-messageExtensions/package.json
js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json
js/samples/03.ai-concepts/d.chainedActions-listBot/package.json
js/samples/03.ai-concepts/e.customModel-LLAMA/package.json
js/samples/03.ai-concepts/f.chatModeration/package.json
js/samples/04.ai-apps/a.teamsChefBot/package.json
js/samples/04.ai-apps/b.devOpsBot/package.json
js/samples/04.ai-apps/c.vision-cardGazer/package.json
js/samples/04.ai-apps/d.assistants-mathBot/package.json
js/samples/04.ai-apps/e.assistants-orderBot/package.json
js/samples/04.ai-apps/f.whoBot/package.json
js/samples/04.ai-apps/g.datasource-azureAISearch/package.json
js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json
js/samples/04.ai-apps/i.teamsChefBot-streaming/package.json
js/samples/05.authentication/a.oauth-adaptiveCard/package.json
js/samples/05.authentication/b.oauth-bot/package.json
js/samples/05.authentication/c.oauth-messageExtension/package.json
js/samples/05.authentication/d.teamsSSO-bot/package.json
js/samples/05.authentication/e.teamsSSO-messageExtension/package.json

[JS] chore: Bump Teams AI JS to 1.6.0

---

js/packages/teams-ai/package.json
js/samples/01.getting-started/a.echoBot/package.json
js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json
js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json
js/samples/03.ai-concepts/a.twentyQuestions/package.json
js/samples/03.ai-concepts/b.AI-messageExtensions/package.json
js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json
js/samples/03.ai-concepts/d.chainedActions-listBot/package.json
js/samples/03.ai-concepts/e.customModel-LLAMA/package.json
js/samples/03.ai-concepts/f.chatModeration/package.json
js/samples/04.ai-apps/a.teamsChefBot/package.json
js/samples/04.ai-apps/b.devOpsBot/package.json
js/samples/04.ai-apps/c.vision-cardGazer/package.json
js/samples/04.ai-apps/d.assistants-mathBot/package.json
js/samples/04.ai-apps/e.assistants-orderBot/package.json
js/samples/04.ai-apps/f.whoBot/package.json
js/samples/04.ai-apps/g.datasource-azureAISearch/package.json
js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json
js/samples/04.ai-apps/i.teamsChefBot-streaming/package.json
js/samples/05.authentication/a.oauth-adaptiveCard/package.json
js/samples/05.authentication/b.oauth-bot/package.json
js/samples/05.authentication/c.oauth-messageExtension/package.json
js/samples/05.authentication/d.teamsSSO-bot/package.json
js/samples/05.authentication/e.teamsSSO-messageExtension/package.json

[JS] chore: `1.6.1`

---

.github/CODEOWNERS

closes: #minor
* Add rajan-chari to CODEOWNERS for JS, .NET, and Python

[repo] fix: Update CODEOWNERS

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Tokenizers/GPTTokenizer.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj

[C#] fix: Upgrade tokenizers library to the GA version 1.0.0

---

js/.gitignore
js/packages/teams-ai/package.json
js/samples/01.getting-started/a.echoBot/package.json
js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json
js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json
js/samples/03.ai-concepts/a.twentyQuestions/package.json
js/samples/03.ai-concepts/b.AI-messageExtensions/package.json
js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json
js/samples/03.ai-concepts/d.chainedActions-listBot/package.json
js/samples/03.ai-concepts/e.customModel-LLAMA/package.json
js/samples/03.ai-concepts/f.chatModeration/package.json
js/samples/04.ai-apps/a.teamsChefBot/package.json
js/samples/04.ai-apps/b.devOpsBot/package.json
js/samples/04.ai-apps/c.vision-cardGazer/package.json
js/samples/04.ai-apps/d.assistants-mathBot/package.json
js/samples/04.ai-apps/e.assistants-orderBot/devTools/teamsapptester
js/samples/04.ai-apps/e.assistants-orderBot/package.json
js/samples/04.ai-apps/f.whoBot/package.json
js/samples/04.ai-apps/g.datasource-azureAISearch/package.json
js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json
js/samples/04.ai-apps/i.teamsChefBot-streaming/package.json
js/samples/05.authentication/a.oauth-adaptiveCard/package.json
js/samples/05.authentication/b.oauth-bot/package.json
js/samples/05.authentication/c.oauth-messageExtension/package.json
js/samples/05.authentication/d.teamsSSO-bot/package.json
js/samples/05.authentication/e.teamsSSO-messageExtension/package.json
js/yarn.lock

[JS] chore: Release 1.7.0

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI.Tests/AITests/LLMClientTests.cs
dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj

- Bumping `JsonSchema` to v6.1.2 so that it uses `Json.More.Net` version 2.x
- Fixed a test failure in a previous PR (.net build was not run)
_Exception_
```
Microsoft.Teams.AI.Exceptions.TeamsAIException: Error while loading prompt. Method not found: \u0027!!0 Json.More.JsonSerializerOptionsExtensions.Read(System.Text.Json.JsonSerializerOptions, System.Text.Json.Utf8JsonReader ByRef)\u0027.\r\n   at Microsoft.Teams.AI.AI.Prompts.PromptManager._LoadPromptTemplateFromFile(String name)\r\n   at Microsoft.Teams.AI.AI.Prompts.PromptManager.GetPrompt(String name)\r\n   at Program.\u003C\u003Ec__DisplayClass0_1.\u003C\u003C\u003CMain\u003E$\u003Eb__14\u003Ed.MoveNext() in C:\\TFS\\Icertis.AI.M365Copilot\\Icertis.AI.M365Copilot.App\\Program.cs:line 148\r\n--- End of …
```

[C#] fix: failure to load prompt due to json serialization error

---

dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj
dotnet/samples/01.messaging.echoBot/EchoBot.csproj
dotnet/samples/02.messageExtensions.a.searchCommand/SearchCommand.csproj
dotnet/samples/03.adaptiveCards.a.typeAheadBot/TypeAheadBot.csproj
dotnet/samples/04.ai.a.teamsChefBot/TeamsChefBot.csproj
dotnet/samples/04.ai.b.messageExtensions.gptME/GPT.csproj
dotnet/samples/04.ai.c.actionMapping.lightBot/LightBot.csproj
dotnet/samples/04.ai.d.chainedActions.listBot/ListBot.csproj
dotnet/samples/04.ai.e.chainedActions.devOpsBot/DevOpsBot.csproj
dotnet/samples/04.ai.f.vision.cardMaster/CardGazer.csproj
dotnet/samples/04.ai.g.teamsChefBot-streaming/TeamsChefBot.csproj
dotnet/samples/04.e.twentyQuestions/TwentyQuestions.csproj
dotnet/samples/05.chatModeration/ChatModeration.csproj
dotnet/samples/06.assistants.a.mathBot/MathBot.csproj
dotnet/samples/06.assistants.b.orderBot/OrderBot.csproj
dotnet/samples/06.auth.oauth.bot/BotAuth.csproj
dotnet/samples/06.auth.oauth.messageExtension/MessageExtensionAuth.csproj
dotnet/samples/06.auth.teamsSSO.bot/BotAuth.csproj
dotnet/samples/06.auth.teamsSSO.messageExtension/MessageExtensionAuth.csproj
dotnet/samples/08.datasource.azureaisearch/AzureAISearchBot/AzureAISearchBot.csproj
dotnet/samples/08.datasource.azureopenai/AzureOpenAIBot.csproj

- bump .NET sdk to v1.9.0
- bump AdaptiveCards.Templating to v2.x

[C#] bump: dotnet to v1.9.0

---

.github/CODEOWNERS
js/packages/teams-ai/package.json
js/samples/01.getting-started/a.echoBot/package.json
js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json
js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json
js/samples/03.ai-concepts/a.twentyQuestions/package.json
js/samples/03.ai-concepts/b.AI-messageExtensions/package.json
js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json
js/samples/03.ai-concepts/d.chainedActions-listBot/package.json
js/samples/03.ai-concepts/e.customModel-LLAMA/package.json
js/samples/03.ai-concepts/f.chatModeration/package.json
js/samples/04.ai-apps/a.teamsChefBot/package.json
js/samples/04.ai-apps/b.devOpsBot/package.json
js/samples/04.ai-apps/c.vision-cardGazer/package.json
js/samples/04.ai-apps/d.assistants-mathBot/package.json
js/samples/04.ai-apps/e.assistants-orderBot/package.json
js/samples/04.ai-apps/f.whoBot/package.json
js/samples/04.ai-apps/g.datasource-azureAISearch/package.json
js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json
js/samples/04.ai-apps/i.teamsChefBot-streaming/package.json
js/samples/05.authentication/a.oauth-adaptiveCard/package.json
js/samples/05.authentication/b.oauth-bot/package.json
js/samples/05.authentication/c.oauth-messageExtension/package.json
js/samples/05.authentication/d.teamsSSO-bot/package.json
js/samples/05.authentication/e.teamsSSO-messageExtension/package.json

[JS] Bump Teams AI for patch release 1.7.1

---

getting-started/CONCEPTS/STREAMING.md
python/packages/ai/teams/ai/clients/llm_client.py
python/packages/ai/teams/ai/models/openai_model.py
python/packages/ai/teams/streaming/__init__.py
python/packages/ai/teams/streaming/streaming_response.py
python/packages/ai/tests/streaming/test_streaming_response.py
python/samples/04.ai.c.actionMapping.lightBot/src/bot.py

closes: #2098, #2212
- enable streaming with tools augmentation
- update lightbot to support streaming

[PY] feat: tools & streaming

---

python/packages/ai/pyproject.toml
python/samples/01.messaging.a.echoBot/pyproject.toml
python/samples/02.messageExtensions.a.searchCommand/pyproject.toml
python/samples/03.adaptiveCards.a.typeAheadBot/pyproject.toml
python/samples/04.ai.a.twentyQuestions/pyproject.toml
python/samples/04.ai.b.messageExtensions.AI-ME/pyproject.toml
python/samples/04.ai.c.actionMapping.lightBot/pyproject.toml
python/samples/04.ai.d.chainedActions.listBot/pyproject.toml
python/samples/04.ai.e.chainedActions.devOpsBot/pyproject.toml
python/samples/04.ai.f.dataSource.azureOpenAI/pyproject.toml
python/samples/04.ai.g.autogen.product-spec-critique/pyproject.toml
python/samples/04.ai.h.chainedActions.listBot-streaming/pyproject.toml
python/samples/05.chatModeration/pyproject.toml
python/samples/06.assistants.a.mathBot/pyproject.toml
python/samples/06.assistants.b.orderBot/pyproject.toml
python/samples/06.auth.oauth.bot/pyproject.toml
python/samples/06.auth.oauth.messageExtensions/pyproject.toml
python/samples/07.planners.a.langchain/pyproject.toml

closes: #minor
- package minor updates 

[PY] bump: minor bump to 1.6.0

---

js/samples/04.ai-apps/b.devOpsBot/package.json
js/samples/04.ai-apps/c.vision-cardGazer/package.json
js/samples/04.ai-apps/d.assistants-mathBot/package.json
js/samples/04.ai-apps/e.assistants-orderBot/package.json
js/samples/04.ai-apps/f.whoBot/package.json
js/samples/04.ai-apps/g.datasource-azureAISearch/package.json
js/samples/04.ai-apps/i.teamsChefBot-streaming/package.json
js/samples/04.ai-apps/i.teamsChefBot-streaming/teamsapp.local.yml

closes: #minor
- Update ttk yml file to install dependencies in streaming sample
- Update openai version in streaming sample
- Update samples to use latest teams-ai where I missed them in some places

[JS] fix: Fix samples deps

---

js/samples/04.ai-apps/i.teamsChefBot-streaming/README.md
js/samples/04.ai-apps/i.teamsChefBot-streaming/src/VectraDataSource.ts
js/samples/04.ai-apps/i.teamsChefBot-streaming/src/index.ts

closes: #2299
- Minor cleanup of streaming `index.ts`
- Changed likely embedding deployment name in `VectraDataSource`
- Add note to change embeddings settings in `VectraDataSource` in the README.md
- Other minor cleanup of README.md

[JS] chore: Add clarity to chef bot README's

---

dotnet/samples/06.assistants.b.orderBot/infra/azure.bicep

#minor
Fix a comma causing invalid syntax
Fix variable name to match

[repo] fix: issues in sample

---

python/packages/ai/teams/ai/models/openai_model.py

closes: #2298
see above and #2345

[PY] fix: updated prefix for o1 and added support for o3

---

.github/workflows/dotnet-build-test-lint.yml
.github/workflows/dotnet-codeql.yml

closes: #minor
* Update pipeline to use .NET 8

[C#] chore: Update dotnet-codeql.yml

---

js/packages/teams-ai/package.json
js/samples/01.getting-started/a.echoBot/package.json
js/samples/02.teams-features/a.messageExtensions.searchCommand/package.json
js/samples/02.teams-features/b.adaptiveCards.typeAheadBot/package.json
js/samples/03.ai-concepts/a.twentyQuestions/package.json
js/samples/03.ai-concepts/b.AI-messageExtensions/package.json
js/samples/03.ai-concepts/c.actionMapping-lightBot/package.json
js/samples/03.ai-concepts/d.chainedActions-listBot/package.json
js/samples/03.ai-concepts/e.customModel-LLAMA/package.json
js/samples/03.ai-concepts/f.chatModeration/package.json
js/samples/04.ai-apps/a.teamsChefBot/package.json
js/samples/04.ai-apps/b.devOpsBot/package.json
js/samples/04.ai-apps/c.vision-cardGazer/package.json
js/samples/04.ai-apps/d.assistants-mathBot/package.json
js/samples/04.ai-apps/e.assistants-orderBot/package.json
js/samples/04.ai-apps/f.whoBot/package.json
js/samples/04.ai-apps/g.datasource-azureAISearch/package.json
js/samples/04.ai-apps/h.datasource-azureOpenAI/package.json
js/samples/04.ai-apps/i.teamsChefBot-streaming/package.json
js/samples/05.authentication/a.oauth-adaptiveCard/package.json
js/samples/05.authentication/b.oauth-bot/package.json
js/samples/05.authentication/c.oauth-messageExtension/package.json
js/samples/05.authentication/d.teamsSSO-bot/package.json
js/samples/05.authentication/e.teamsSSO-messageExtension/package.json
js/yarn.lock

[JS] Bump 1.7.4

---

.github/workflows/deploy.yml

Forgot to add this preprocessor to the github actions

Add alerts mdbook preprocessor

---

.github/workflows/deploy-docs.yml

Allow docs to deploy on manual trigger
Or allow them to also trigger if there's any changes to the workflow

Allow docs to deploy on manual trigger

---

README.md
book/README.md
book/book.toml
book/src/1.welcome/README.md
book/src/2.getting-started/1.create-application.md
book/src/2.getting-started/2.anatomy-of-an-app.md
book/src/2.getting-started/README.md
book/src/5.in-depth-guides/1.cards/2.executing-actions.md
book/src/5.in-depth-guides/5.ai/6.external/1.mcp.md

SDK -> Library

---

README.md
book/src/1.welcome/README.md

Updated welcome docs

---

README.md
book/src/1.welcome/README.md

Fixed CLI commands being in one text block so they can easily be copied separately into the CLI.

Fixed cli commands in welcome page & README

---

book/src/SUMMARY.md

This is annoyingly not working as expected

Remove comments in Summary.md

---

book/generated-snippets/ts/card.snippet.message-ext-create-card.ts
book/generated-snippets/ts/card.snippet.message-ext-create-conversation-members-card.ts
book/generated-snippets/ts/card.snippet.message-ext-create-dummy-cards.ts
book/generated-snippets/ts/card.snippet.message-ext-create-link-unfurl-card.ts
book/generated-snippets/ts/card.snippet.message-ext-create-message-details-card.ts
book/generated-snippets/ts/index.snippet.basic-card-building.ts
book/generated-snippets/ts/index.snippet.dialog-entry-point.ts
book/generated-snippets/ts/index.snippet.dialog-multi-step-step-1.ts
book/generated-snippets/ts/index.snippet.dialog-open.ts
book/generated-snippets/ts/index.snippet.dialog-simple-card.ts
book/generated-snippets/ts/index.snippet.dialog-submission-multistep.ts
book/generated-snippets/ts/index.snippet.form-card.ts
book/generated-snippets/ts/index.snippet.input-validation.ts
book/generated-snippets/ts/index.snippet.inputs-included.ts
book/generated-snippets/ts/index.snippet.message-ext-submit.ts
book/generated-snippets/ts/index.snippet.raw-card-json.ts
book/generated-snippets/ts/index.snippet.sending-adaptive-card-e2e.ts
book/generated-snippets/ts/index.snippet.task-form-card.ts
book/src/in-depth-guides/cards/building-adaptive-cards.md
book/src/in-depth-guides/dialogs/creating-dialogs.md

This PR updates the V2 Preview documentation for Adaptive Cards to reflect the changes made to replace the manually generated code in `teams.cards` with auto-generated code.
The changes are minor, and only update names for classes and methods.

V2 Preview documentation update for Adaptive Cards

---

README.md

[repo] chore: update README for v2 

---

teams.md/src/css/custom.css

Makes links at the top seem more clickable and make it more obvious that they're active.
https://github.com/user-attachments/assets/501c2217-22cd-4cf7-befc-8fc8414a91d0

Add active-page link

---

python/packages/ai/teams/ai/planners/action_planner.py

[PY] fix: fix issue chat History Limitation Problem

---

teams.md/docs/csharp/essentials/api.mdx
teams.md/docs/csharp/essentials/sending-messages/proactive-messaging.mdx
teams.md/docs/python/essentials/api.md
teams.md/docs/python/essentials/sending-messages/proactive-messaging.md
teams.md/docs/typescript/essentials/api.md
teams.md/docs/typescript/essentials/on-activity/README.md
teams.md/docs/typescript/essentials/on-activity/activity-ref.md
teams.md/docs/typescript/essentials/sending-messages/proactive-messaging.mdx

Light editorial pass of the "essentials" docs
For c#, typescript, and python:
- api.md - Made sure API was capitalized when appropriate. 
- proactive-messaging.md - Small edits.
- readme.md (typescript only) - Removed duplicate h1.
- activity-ref.md - Changed a comma to a colon.
- [NA] I have commented my code for clarity
- [NA] I have added tests that validates my changes, and provides sufficient test coverage. I have tested with:
- [NA] New and existing unit tests pass locally with my changes
Previously was PR to v2-preview, recreated for Main https://github.com/microsoft/teams-ai/pull/2598

Doc review pass of essentials section

---

scripts/generate-snippets.js
teams.md/docs/csharp/in-depth-guides/feedback.mdx

Update with hardcoded C# examples rather than TS.

[docs] Update C# feedback docs
